/** verify/bridge-drift — cheap drift detection for the Kani bridge pilot.
 *
 * The pilot's proofs (verify/rust-bridge/src/proofs.rs) run against the
 * production `algal` crate by path dependency, so a passing badge can silently
 * outlive the code it proved. This lane binds the exact inputs the evidence
 * depends on:
 *
 *   - every regular file under verify/rust-bridge (harnesses, crate manifest,
 *     lockfile, run script, docs — the whole evidence package), except the
 *     generated `target/` build tree;
 *   - each top-level `fn`/`const` item of crates/algal/src/canonical.rs that
 *     the harnesses exercise (including the private `array_index`/`key_order`
 *     helpers reached through `canonical`), bound by byte digest of the item
 *     source, plus a whole-file digest for everything outside named items;
 *   - the `#[kani::proof]` harness inventory in proofs.rs.
 *
 * `computeBindings` produces the record; `bindings.json` in this directory is
 * the recorded baseline; `drift.test.ts` fails with a per-input diff whenever
 * the current tree and the recording differ. Refresh with
 * `bun verify/bridge-drift/bind.ts` only after the proof has been re-run.
 */
import { readdir } from "node:fs/promises";
import { join } from "node:path";
import { hashBytes, hashFile, readFileBounded } from "../lib/files";
import { array, digest, record, relativePath, requireThat, string, strings } from "../lib/schema";

export const BRIDGE_DIR = "verify/rust-bridge";
export const PROOF_TARGET = "crates/algal/src/canonical.rs";
export const HARNESS_SOURCE = `${BRIDGE_DIR}/src/proofs.rs`;
export const BINDINGS_PATH = "verify/bridge-drift/bindings.json";
export const CONTRACT = "algal.bridge-drift.v1";

/** Every top-level item of canonical.rs the proofs touch. `check_digest` and
 * `canonical` are the harnessed public surfaces; `encode`/`key_order`/
 * `array_index` are the private closure `canonical` depends on; `read_json`,
 * `digest`, `digest_bytes` and `MAX_DOCUMENT_BYTES` are exercised by the
 * sanity suite and bound so the withdrawn read_json proof surface still
 * reports drift instead of going quiet. */
export const SYMBOLS = ["MAX_DOCUMENT_BYTES", "read_json", "array_index", "key_order", "encode", "canonical", "digest_bytes", "digest", "check_digest"] as const;

/** The walk must cover at least these inputs; an under-collecting walk fails
 * even if the recorded file was generated by the same code. */
export const REQUIRED_INPUTS = [
  `${BRIDGE_DIR}/Cargo.toml`, `${BRIDGE_DIR}/Cargo.lock`, `${BRIDGE_DIR}/run.sh`,
  `${BRIDGE_DIR}/src/lib.rs`, `${BRIDGE_DIR}/src/proofs.rs`, `${BRIDGE_DIR}/src/sanity.rs`,
] as const;

export type BridgeBindings = {
  contract: typeof CONTRACT;
  inputs: { path: string; sha256: string }[];
  proofTarget: { path: string; sha256: string };
  symbols: { symbol: string; sha256: string }[];
  harnesses: string[];
};

/** Copy of `source` with every comment, string, char and raw-string literal
 * blanked to spaces (newlines preserved). Brace depth computed over the masked
 * text never sees literal braces such as `'{'` or `"{:x}"`. */
export function maskRust(source: string): string {
  const out = source.split("");
  const n = source.length;
  const blank = (from: number, to: number): void => {
    for (let k = from; k < to; k++) if (out[k] !== "\n") out[k] = " ";
  };
  const ident = (c: string | undefined): boolean => c !== undefined && /[A-Za-z0-9_]/.test(c);
  let i = 0;
  while (i < n) {
    const c = source[i]!;
    if (c === "/" && source[i + 1] === "/") {
      let j = source.indexOf("\n", i); if (j === -1) j = n;
      blank(i, j); i = j;
    } else if (c === "/" && source[i + 1] === "*") {
      // Rust block comments nest.
      let depth = 1, j = i + 2;
      while (j < n && depth > 0) {
        if (source[j] === "*" && source[j + 1] === "/") { depth--; j += 2; }
        else if (source[j] === "/" && source[j + 1] === "*") { depth++; j += 2; }
        else j++;
      }
      requireThat(depth === 0, "unterminated Rust block comment");
      blank(i, j); i = j;
    } else if (c === "r" && !ident(source[i - 1]) && (source[i + 1] === '"' || (source[i + 1] === "#" && source[i + 2] === '"'))) {
      // Raw strings r"..." / r#"..."# .. r###"..."### (three hashes bound it).
      let hashes = 0, j = i + 1;
      while (source[j] === "#") { hashes++; j++; }
      requireThat(hashes <= 3 && source[j] === '"', "unrecognized Rust raw string");
      const close = `"${"#".repeat(hashes)}`;
      const end = source.indexOf(close, j + 1);
      requireThat(end !== -1, "unterminated Rust raw string");
      blank(i, end + close.length); i = end + close.length;
    } else if (c === '"') {
      let j = i + 1;
      while (j < n && source[j] !== '"') { if (source[j] === "\\") j++; j++; }
      requireThat(j < n, "unterminated Rust string literal");
      blank(i, j + 1); i = j + 1;
    } else if (c === "'") {
      if (source[i + 1] === "\\") {
        // Escaped char literal '\n', '\'', '\u{1F}': bounded scan to the quote.
        let j = i + 2;
        while (j < n && source[j] !== "'" && j - i <= 12) j++;
        requireThat(j < n && source[j] === "'", "unterminated Rust char literal");
        blank(i, j + 1); i = j + 1;
      } else if (i + 2 < n && source[i + 2] === "'") {
        blank(i, i + 3); i += 3; // 'x'
      } else i++; // lifetime like 'a — not a literal, move past the quote
    } else i++;
  }
  return out.join("");
}

/** Top-level `fn`/`const` item sources keyed by item name. The returned text
 * is the exact source span from the item's first keyword through its closing
 * brace (functions) or terminating semicolon (consts), so a formatting,
 * signature or body change all move the digest. Doc comments and attributes
 * are excluded from the span; the whole-file digest still covers them. */
export function rustItems(source: string): Map<string, string> {
  requireThat(source.length > 0 && source.length <= 4_194_304, "Rust source bound");
  const masked = maskRust(source);
  const found = new Map<string, string>();
  const n = masked.length;
  let depth = 0, i = 0;
  while (i < n) {
    const c = masked[i]!;
    if (c === "{") { depth++; i++; continue; }
    if (c === "}") { depth--; requireThat(depth >= 0, "unbalanced Rust braces"); i++; continue; }
    if (depth === 0 && (i === 0 || masked[i - 1] === "\n")) {
      let eol = masked.indexOf("\n", i); if (eol === -1) eol = n;
      const line = masked.slice(i, eol);
      const item = /^\s*(?:#\[[^\n\]]*\]\s*)*(?:pub(?:\s*\([^()]*\))?\s+)?(?:unsafe\s+)?(fn|const)\s+([A-Za-z_][A-Za-z0-9_]*)/.exec(line);
      if (item) {
        const name = item[2]!;
        const start = i + (item[0].length - item[0].trimStart().length);
        // The first `{` or `;` after the item keyword ends the signature:
        // neither can appear inside a Rust signature, so `const` items stop
        // at their `;` even on the same line and `fn` items at their body.
        let j = start, end = -1;
        while (j < n) {
          const ch = masked[j]!;
          if (ch === ";") { end = j + 1; break; }
          if (ch === "{") {
            let inner = 1, k = j + 1;
            while (k < n && inner > 0) {
              if (masked[k] === "{") inner++;
              else if (masked[k] === "}") inner--;
              k++;
            }
            requireThat(inner === 0, `${name}: unbalanced braces`);
            end = k; break;
          }
          j++;
        }
        requireThat(end !== -1, `${name}: item body or terminator not found`);
        requireThat(!found.has(name), `duplicate top-level Rust item ${name}`);
        found.set(name, source.slice(start, end));
        i = end; continue;
      }
    }
    i++;
  }
  return found;
}

/** `#[kani::proof]` harness names in declaration order. */
export function kaniHarnesses(source: string): string[] {
  requireThat(source.length > 0 && source.length <= 4_194_304, "harness source bound");
  const names: string[] = [];
  let from = 0;
  for (;;) {
    const at = source.indexOf("#[kani::proof]", from);
    if (at === -1) break;
    const window = source.slice(at, at + 4096);
    const name = /\bfn\s+([a-z_][a-z0-9_]*)/.exec(window);
    requireThat(name !== null, "#[kani::proof] without a following fn");
    names.push(name[1]!);
    from = at + "#[kani::proof]".length;
  }
  requireThat(names.length > 0 && names.length <= 64 && new Set(names).size === names.length, "kani harness inventory bound");
  return names;
}

/** Bind every regular file under verify/rust-bridge except the generated
 * `target/` build tree, then the proof target's per-item and whole-file
 * digests, then the harness inventory. */
export async function computeBindings(root: string): Promise<BridgeBindings> {
  const paths: string[] = [];
  let visited = 0;
  async function walk(relative: string): Promise<void> {
    for (const entry of await readdir(join(root, BRIDGE_DIR, relative), { withFileTypes: true })) {
      requireThat(++visited <= 512, "bridge input inventory bound");
      const child = relative ? `${relative}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        if (entry.name === "target") continue; // generated build output
        await walk(child); continue;
      }
      requireThat(entry.isFile() && !entry.isSymbolicLink(), `${BRIDGE_DIR}/${child}: nonregular bridge input`);
      paths.push(`${BRIDGE_DIR}/${child}`);
    }
  }
  await walk("");
  paths.sort();
  const inputs: { path: string; sha256: string }[] = [];
  for (const path of paths) inputs.push({ path, sha256: await hashFile(root, path) });
  const targetBytes = await readFileBounded(root, PROOF_TARGET);
  const targetText = new TextDecoder("utf-8", { fatal: true }).decode(targetBytes);
  const items = rustItems(targetText);
  const symbols = SYMBOLS.map(symbol => {
    const span = items.get(symbol);
    requireThat(span !== undefined, `${PROOF_TARGET}: harnessed symbol ${symbol} not found`);
    return { symbol, sha256: hashBytes(span) };
  });
  const harnessText = new TextDecoder("utf-8", { fatal: true }).decode(await readFileBounded(root, HARNESS_SOURCE));
  return { contract: CONTRACT, inputs, proofTarget: { path: PROOF_TARGET, sha256: hashBytes(targetBytes) }, symbols, harnesses: kaniHarnesses(harnessText) };
}

export function parseBindings(value: unknown): BridgeBindings {
  const item = record(value, ["contract", "inputs", "proofTarget", "symbols", "harnesses"], "bridge bindings");
  requireThat(item.contract === CONTRACT, "unknown bridge bindings contract");
  const inputs = array(item.inputs, "bridge inputs", 1, 512).map((v, i) => {
    const f = record(v, ["path", "sha256"], `bridge input ${i}`);
    return { path: relativePath(f.path, `bridge input ${i}.path`), sha256: digest(f.sha256, `bridge input ${i}.sha256`) };
  });
  requireThat(new Set(inputs.map(f => f.path)).size === inputs.length, "duplicate bridge input path");
  const target = record(item.proofTarget, ["path", "sha256"], "bridge proof target");
  const symbols = array(item.symbols, "bridge symbols", 1, 256).map((v, i) => {
    const s = record(v, ["symbol", "sha256"], `bridge symbol ${i}`);
    return { symbol: string(s.symbol, `bridge symbol ${i}.symbol`, 256), sha256: digest(s.sha256, `bridge symbol ${i}.sha256`) };
  });
  requireThat(new Set(symbols.map(s => s.symbol)).size === symbols.length, "duplicate bridge symbol");
  return {
    contract: CONTRACT, inputs, symbols,
    proofTarget: { path: relativePath(target.path, "bridge proof target path"), sha256: digest(target.sha256, "bridge proof target sha256") },
    harnesses: strings(item.harnesses, "bridge harnesses", 1, 64),
  };
}

/** Human-readable drift lines; empty means the recorded evidence still
 * describes the current tree. */
export function diffBindings(recorded: BridgeBindings, actual: BridgeBindings): string[] {
  const diffs: string[] = [];
  const recordedInputs = new Map(recorded.inputs.map(f => [f.path, f.sha256]));
  const actualInputs = new Map(actual.inputs.map(f => [f.path, f.sha256]));
  for (const f of actual.inputs) {
    const was = recordedInputs.get(f.path);
    if (was === undefined) diffs.push(`added bridge input ${f.path} is not covered by the recorded bindings`);
    else if (was !== f.sha256) diffs.push(`changed bridge input ${f.path} (${was} -> ${f.sha256})`);
  }
  for (const f of recorded.inputs) if (!actualInputs.has(f.path)) diffs.push(`recorded bridge input ${f.path} is missing from the tree`);
  if (recorded.proofTarget.path !== actual.proofTarget.path || recorded.proofTarget.sha256 !== actual.proofTarget.sha256)
    diffs.push(`proof target ${actual.proofTarget.path} changed (${recorded.proofTarget.sha256} -> ${actual.proofTarget.sha256})`);
  const recordedSymbols = new Map(recorded.symbols.map(s => [s.symbol, s.sha256]));
  const actualSymbols = new Map(actual.symbols.map(s => [s.symbol, s.sha256]));
  for (const s of actual.symbols) {
    const was = recordedSymbols.get(s.symbol);
    if (was === undefined) diffs.push(`added harnessed symbol ${s.symbol}`);
    else if (was !== s.sha256) diffs.push(`changed harnessed symbol ${s.symbol} (${was} -> ${s.sha256})`);
  }
  for (const s of recorded.symbols) if (!actualSymbols.has(s.symbol)) diffs.push(`recorded harnessed symbol ${s.symbol} is gone`);
  if (JSON.stringify(recorded.harnesses) !== JSON.stringify(actual.harnesses))
    diffs.push(`kani harness inventory changed (recorded ${JSON.stringify(recorded.harnesses)} -> actual ${JSON.stringify(actual.harnesses)})`);
  return diffs;
}
