import Algal.Core.All

/-! Diagnostic only; release admission independently queries actual theorem constants. -/

#print axioms Algal.Core.Binary64.admit_number
#print axioms Algal.Core.Binary64.normalizeBits_idempotent
#print axioms Algal.Core.Binary64.normalizeBits_finite
#print axioms Algal.Core.Binary64.normalizeBits_not_negativeZero
#print axioms Algal.Core.Binary64.normalize_idempotent
#print axioms Algal.Core.Binary64.normalize_eq_self
#print axioms Algal.Core.Binary64.equivalent_normalized_iff
#print axioms Algal.Core.Binary64.normalizeBits_changes_only_negativeZero
#print axioms Algal.Core.Binary64.admit_none_iff
#print axioms Algal.Core.Binary64.admitted_bits
#print axioms Algal.Core.Binary64.signed_zero_equivalent
#print axioms Algal.Core.Binary64.signed_zero_bits_differ
#print axioms Algal.Core.Binary64.minimum_subnormal_admitted
#print axioms Algal.Core.Binary64.maximum_finite_admitted
#print axioms Algal.Core.Binary64.positive_infinity_rejected
#print axioms Algal.Core.Binary64.negative_infinity_rejected
#print axioms Algal.Core.Binary64.nan_rejected
#print axioms Algal.Core.Binary64.model_addition_witness
#print axioms Algal.Core.Text.scalar_range
#print axioms Algal.Core.Text.utf16Char_length
#print axioms Algal.Core.Text.utf16Char_unit_bound
#print axioms Algal.Core.Text.decodeChar_utf16Char
#print axioms Algal.Core.Text.utf16Char_injective
#print axioms Algal.Core.Text.decodeChars_utf16
#print axioms Algal.Core.Text.utf16_injective
#print axioms Algal.Core.Text.insertKey_preserves_keys
#print axioms Algal.Core.Text.canonicalKeys_preserves_keys
#print axioms Algal.Core.Text.scalar_surrogate_rejected
#print axioms Algal.Core.Text.utf16_supplementary_witness
#print axioms Algal.Core.Text.no_nfc_identification
#print axioms Algal.Core.Text.scalar_order_is_not_utf16_order
#print axioms Algal.Core.Text.index_maximum_admitted
#print axioms Algal.Core.Text.index_overflow_rejected
#print axioms Algal.Core.Text.index_leading_zero_rejected
#print axioms Algal.Core.Text.index_plus_rejected
#print axioms Algal.Core.Text.index_negative_zero_rejected
#print axioms Algal.Core.Text.canonical_key_order_witness
#print axioms Algal.Core.JsonString.hexControl_roundtrip
#print axioms Algal.Core.JsonString.readUnit_escapeChar
#print axioms Algal.Core.JsonString.escapeChar_head
#print axioms Algal.Core.JsonString.scan_escapeChar
#print axioms Algal.Core.JsonString.scan_escapedBody
#print axioms Algal.Core.JsonString.escapeChar_length
#print axioms Algal.Core.JsonString.escapedBody_length
#print axioms Algal.Core.JsonString.readQuoted_quote_suffix
#print axioms Algal.Core.JsonString.fromUTF8_toUTF8
#print axioms Algal.Core.JsonString.quoteBytes_utf8
#print axioms Algal.Core.JsonString.quotedBytes_roundtrip
#print axioms Algal.Core.JsonString.quotedBytes_injective
#print axioms Algal.Core.JsonString.decodeBytes_roundtrip
#print axioms Algal.Core.JsonString.standard_controls_witness
#print axioms Algal.Core.JsonString.supplementary_utf8_witness
#print axioms Algal.Core.JsonString.malformed_utf8_rejected
#print axioms Algal.Core.JsonString.overlong_utf8_rejected
#print axioms Algal.Core.JsonString.surrogate_utf8_rejected
#print axioms Algal.Core.JsonString.leading_bom_rejected
#print axioms Algal.Core.JsonString.embedded_bom_retained
#print axioms Algal.Core.JsonString.literal_control_rejected
#print axioms Algal.Core.JsonString.escaped_quote_is_content
#print axioms Algal.Core.JsonString.trailing_content_rejected
#print axioms Algal.Core.JsonString.missing_end_quote_rejected
#print axioms Algal.Core.JsonString.invalid_escape_rejected
#print axioms Algal.Core.OwnMap.lookup_write_same
#print axioms Algal.Core.OwnMap.lookup_write_other
#print axioms Algal.Core.OwnMap.overwrite_last_wins
#print axioms Algal.Core.OwnMap.distinct_writes_commute
#print axioms Algal.Core.OwnMap.lookup_defined_only_if_declared
#print axioms Algal.Core.OwnMap.lookup_absent_if_undeclared
#print axioms Algal.Core.OwnMap.parsed_duplicate_witness
#print axioms Algal.Core.OwnMap.insertion_order_witness
#print axioms Algal.Core.OwnMap.inherited_name_absent
#print axioms Algal.Core.OwnMap.proto_name_is_an_own_key
#print axioms Algal.Core.OwnMap.absent_is_not_present_none
#print axioms Algal.Core.Json.normalizeNumbers_idempotent
#print axioms Algal.Core.Json.normalizeItems_idempotent
#print axioms Algal.Core.Json.normalizeFields_idempotent
#print axioms Algal.Core.Json.execute_append
#print axioms Algal.Core.Json.execute_encode
#print axioms Algal.Core.Json.execute_encodeItems
#print axioms Algal.Core.Json.execute_encodeFields
#print axioms Algal.Core.Json.structural_roundtrip
#print axioms Algal.Core.Json.structural_encoding_injective
#print axioms Algal.Core.Json.structural_roundtrip_modulo_number_normalization
#print axioms Algal.Core.Json.normalized_structural_encoding_eq_iff
#print axioms Algal.Core.Json.malformed_stack_rejected
#print axioms Algal.Core.Json.nonfinite_token_rejected
#print axioms Algal.Core.Json.extra_value_rejected
#print axioms Algal.Core.Json.array_order_is_significant
#print axioms Algal.Core.Json.nested_structural_witness
#print axioms Algal.Core.Normalize.fieldsToList_ofList
#print axioms Algal.Core.Normalize.fieldsOfList_toList
#print axioms Algal.Core.Normalize.lookup_append
#print axioms Algal.Core.Normalize.lookupFields_cons
#print axioms Algal.Core.Normalize.lookup_map
#print axioms Algal.Core.Normalize.canonicalEntries_lookup
#print axioms Algal.Core.Normalize.canonicalEntries_eq_of_equivalent
#print axioms Algal.Core.Normalize.canonicalEntries_fallback_irrelevant
#print axioms Algal.Core.Normalize.canonicalEntries_keys
#print axioms Algal.Core.Normalize.canonicalEntries_nodup
#print axioms Algal.Core.Normalize.canonicalEntries_sorted
#print axioms Algal.Core.Normalize.lookup_reverse_unique
#print axioms Algal.Core.Normalize.canonicalFields_lookup
#print axioms Algal.Core.Normalize.canonicalFields_eq_of_lookup
#print axioms Algal.Core.Normalize.canonicalFields_nodup
#print axioms Algal.Core.Normalize.canonicalFields_sorted
#print axioms Algal.Core.Normalize.normalizeItems_toList
#print axioms Algal.Core.Normalize.normalizeItems_length
#print axioms Algal.Core.Normalize.normalizeFieldValues_lookup
#print axioms Algal.Core.Normalize.normalize_object_lookup
#print axioms Algal.Core.Normalize.numberEquivalent_iff_normalize
#print axioms Algal.Core.Normalize.equivalent_normalize
#print axioms Algal.Core.Normalize.equivalent_symm
#print axioms Algal.Core.Normalize.equivalent_trans
#print axioms Algal.Core.Normalize.normalize_sound
#print axioms Algal.Core.Normalize.normalizeItems_sound
#print axioms Algal.Core.Normalize.normalizeFieldValues_sound
#print axioms Algal.Core.Normalize.normalize_idempotent
#print axioms Algal.Core.Normalize.equivalent_iff_normalize_eq
#print axioms Algal.Core.Normalize.equivalent_refl
#print axioms Algal.Core.Normalize.canonicalTokens_roundtrip
#print axioms Algal.Core.Normalize.canonicalTokens_eq_iff
#print axioms Algal.Core.Normalize.canonicalTokens_normalize
#print axioms Algal.Core.Normalize.decoded_canonicalTokens_equivalent
#print axioms Algal.Core.Normalize.canonicalTokens_injective_on_normalized
#print axioms Algal.Core.Normalize.nested_normalization_witness
#print axioms Algal.Core.Normalize.nested_equivalence_witness
#print axioms Algal.Core.Normalize.signed_zero_normalization_witness
#print axioms Algal.Core.Normalize.overwritten_duplicate_ignored
#print axioms Algal.Core.Normalize.reordered_distinct_keys_witness
#print axioms Algal.Core.Normalize.changed_duplicate_winner_rejected
#print axioms Algal.Core.Normalize.array_permutation_rejected
#print axioms Algal.Core.Normalize.absent_and_present_null_rejected
#print axioms Algal.Core.Normalize.inherited_name_stays_absent
#print axioms Algal.Core.Normalize.proto_is_retained_own_key
#print axioms Algal.Core.Normalize.unicode_normalization_not_applied
#print axioms Algal.Core.Ports.capability_no_json_widening
#print axioms Algal.Core.Ports.capability_class_preserved
#print axioms Algal.Core.Ports.reference_is_not_payload
#print axioms Algal.Core.Ports.many_to_scalar_nonjson_rejected
#print axioms Algal.Core.Ports.accepted_value_byte_bound
#print axioms Algal.Core.Ports.accepted_scalar_capability_class
#print axioms Algal.Core.Ports.accepted_many_is_array
#print axioms Algal.Core.Ports.checked_assignment_preserves_types
#print axioms Algal.Core.Ports.undeclared_assignment_rejected
#print axioms Algal.Core.Ports.signature_does_not_imply_schema_satisfaction
#print axioms Algal.Core.Ports.open_choice_does_not_imply_label_satisfaction
#print axioms Algal.Core.Ports.many_to_json_witness
#print axioms Algal.Core.Ports.capability_syntax_witness
#print axioms Algal.Core.Ports.capability_wrong_class_rejected
#print axioms Algal.Core.Ports.empty_digest_rejected
#print axioms Algal.Core.Ports.inherited_port_rejected
#print axioms Algal.Core.Ports.syntax_does_not_mint_authority
#print axioms Algal.Core.Graph.accepted_edge_resolves_own_ports
#print axioms Algal.Core.Graph.ownOutput_is_declared
#print axioms Algal.Core.Graph.ownInput_is_declared
#print axioms Algal.Core.Graph.interfaceInput_is_declared_input_cell
#print axioms Algal.Core.Graph.accepted_interface_input_resolves
#print axioms Algal.Core.Graph.accepted_interface_output_resolves
#print axioms Algal.Core.Graph.accepted_edge_increases_rank
#print axioms Algal.Core.Graph.accepted_path_increases_rank
#print axioms Algal.Core.Graph.accepted_graph_acyclic
#print axioms Algal.Core.Graph.accepted_scalar_cardinality
#print axioms Algal.Core.Graph.accepted_no_mixed_failure_inputs
#print axioms Algal.Core.Graph.accepted_normal_capability_edge_preserves_class
#print axioms Algal.Core.Graph.accepted_child_output_corresponds
#print axioms Algal.Core.Graph.accepted_child_input_corresponds
#print axioms Algal.Core.Graph.declared_acyclic_graph_admitted
#print axioms Algal.Core.Graph.duplicate_scalar_edge_rejected
#print axioms Algal.Core.Graph.inherited_endpoint_rejected
#print axioms Algal.Core.Graph.self_cycle_rejected
#print axioms Algal.Core.Graph.missing_child_port_rejected
#print axioms Algal.Core.Graph.exact_child_interface_admitted
#print axioms Algal.Core.Accounting.preIncrement_success_bound
#print axioms Algal.Core.Accounting.preIncrement_at_limit_rejected
#print axioms Algal.Core.Accounting.preIncrement_below_limit_admitted
#print axioms Algal.Core.Accounting.postCharge_monotone
#print axioms Algal.Core.Accounting.postCharge_envelope
#print axioms Algal.Core.Accounting.postCharge_success_bound
#print axioms Algal.Core.Accounting.postCharge_failure_retains_charge
#print axioms Algal.Core.Accounting.strict_limit_is_not_an_invariant
#print axioms Algal.Core.Accounting.callback_failure_keeps_cost
#print axioms Algal.Core.Accounting.direct_tool_failure_no_success_charge
#print axioms Algal.Core.Accounting.effect_attempt_base_bound
#print axioms Algal.Core.Accounting.charged_group_envelope
#print axioms Algal.Core.Accounting.uint64_add_without_wrap
#print axioms Algal.Core.Accounting.exact_integer_envelope_fits_uint64
#print axioms Algal.Core.Accounting.admitted_cost_nonnegative
#print axioms Algal.Core.Accounting.negative_callback_cost_rejected
#print axioms Algal.Core.Accounting.excessive_callback_cost_rejected
#print axioms Algal.Core.Accounting.zero_callback_cost_admitted
#print axioms Algal.Core.Accounting.typical_callback_cost_admitted
#print axioms Algal.Core.Oracle.successful_replay_binds_head
#print axioms Algal.Core.Oracle.successful_replay_consumes_exactly_one
#print axioms Algal.Core.Oracle.changed_occurrence_rejected
#print axioms Algal.Core.Oracle.changed_request_rejected
#print axioms Algal.Core.Oracle.replay_deterministic
#print axioms Algal.Core.Oracle.successful_replay_witness
#print axioms Algal.Core.Oracle.same_request_different_occurrence_is_not_replay
#print axioms Algal.Core.Oracle.external_failure_is_replayable
#print axioms Algal.Core.Oracle.reordered_tape_rejected
#print axioms Algal.Core.KeyOrder.digit_char_rebuild
#print axioms Algal.Core.KeyOrder.parseDigits_append_repr
#print axioms Algal.Core.KeyOrder.parseDigits_nonzero_head
#print axioms Algal.Core.KeyOrder.arrayIndex_digits
#print axioms Algal.Core.KeyOrder.arrayIndex_injective
#print axioms Algal.Core.KeyOrder.keyOrder_swap
#print axioms Algal.Core.KeyOrder.keyLE_trans
#print axioms Algal.Core.KeyOrder.keyLE_antisymm
#print axioms Algal.Core.KeyOrder.keyLE_total
#print axioms Algal.Core.KeyOrder.keyOrder_notGT
#print axioms Algal.Core.KeyOrder.insertKey_sorted
#print axioms Algal.Core.KeyOrder.canonicalKeys_sorted
#print axioms Algal.Core.KeyOrder.canonicalKeys_permutation_invariant
#print axioms Algal.Core.KeyOrder.canonicalKeys_idempotent
#print axioms Algal.Core.KeyOrder.lookup_isSome_iff
#print axioms Algal.Core.KeyOrder.eraseDups_nodup
#print axioms Algal.Core.KeyOrder.support_permutation_of_equivalent
#print axioms Algal.Core.KeyOrder.canonicalProjection_eq_of_equivalent
#print axioms Algal.Core.KeyOrder.lookup_keyed_map
#print axioms Algal.Core.KeyOrder.canonicalProjection_lookup
#print axioms Algal.Core.KeyOrder.canonicalProjection_eq_iff
#print axioms Algal.Core.KeyOrder.canonicalProjection_distinct_writes_commute
#print axioms Algal.Core.KeyOrder.changed_duplicate_winner_changes_projection
#print axioms Algal.Core.KeyOrder.reordered_map_witness
