import Algal.Core.All

/-! Diagnostic only; release admission independently queries actual theorem constants. -/

#print axioms Algal.Core.Binary64.admit_number
#print axioms Algal.Core.Binary64.normalizeBits_idempotent
#print axioms Algal.Core.Binary64.normalizeBits_finite
#print axioms Algal.Core.Binary64.normalizeBits_not_negativeZero
#print axioms Algal.Core.Binary64.normalize_idempotent
#print axioms Algal.Core.Binary64.normalize_eq_self
#print axioms Algal.Core.Binary64.equivalent_normalized_iff
#print axioms Algal.Core.Binary64.normalizeBits_changes_only_negativeZero
#print axioms Algal.Core.Binary64.admit_none_iff
#print axioms Algal.Core.Binary64.admitted_bits
#print axioms Algal.Core.Binary64.signed_zero_equivalent
#print axioms Algal.Core.Binary64.signed_zero_bits_differ
#print axioms Algal.Core.Binary64.minimum_subnormal_admitted
#print axioms Algal.Core.Binary64.maximum_finite_admitted
#print axioms Algal.Core.Binary64.positive_infinity_rejected
#print axioms Algal.Core.Binary64.negative_infinity_rejected
#print axioms Algal.Core.Binary64.nan_rejected
#print axioms Algal.Core.Binary64.model_addition_witness
#print axioms Algal.Core.BinaryValue.fraction_lt
#print axioms Algal.Core.BinaryValue.signBit_lt
#print axioms Algal.Core.BinaryValue.fields_recompose
#print axioms Algal.Core.BinaryValue.model_fraction
#print axioms Algal.Core.BinaryValue.model_exponent
#print axioms Algal.Core.BinaryValue.model_signBit
#print axioms Algal.Core.BinaryValue.model_sign
#print axioms Algal.Core.BinaryValue.model_denotation
#print axioms Algal.Core.BinaryValue.model_nonfinite_rejected
#print axioms Algal.Core.BinaryValue.coefficient_lt
#print axioms Algal.Core.BinaryValue.normal_coefficient_lower
#print axioms Algal.Core.BinaryValue.power_bounds
#print axioms Algal.Core.BinaryValue.exact_subnormal
#print axioms Algal.Core.BinaryValue.exact_normal
#print axioms Algal.Core.BinaryValue.exact_rational
#print axioms Algal.Core.BinaryValue.subnormal_rational
#print axioms Algal.Core.BinaryValue.sign_apply_zero_iff
#print axioms Algal.Core.BinaryValue.dyadic_zero_iff
#print axioms Algal.Core.BinaryValue.coefficient_zero_iff
#print axioms Algal.Core.BinaryValue.zero_fields_iff
#print axioms Algal.Core.BinaryValue.exact_zero_iff
#print axioms Algal.Core.BinaryValue.exact_positive_zero
#print axioms Algal.Core.BinaryValue.exact_negative_zero
#print axioms Algal.Core.BinaryValue.normalization_preserves_denotation
#print axioms Algal.Core.BinaryValue.equivalent_denotation
#print axioms Algal.Core.BinaryValue.minimum_subnormal_value
#print axioms Algal.Core.BinaryValue.negative_minimum_subnormal_value
#print axioms Algal.Core.BinaryValue.minimum_normal_value
#print axioms Algal.Core.BinaryValue.one_value
#print axioms Algal.Core.BinaryValue.negative_one_value
#print axioms Algal.Core.BinaryValue.maximum_finite_value
#print axioms Algal.Core.BinaryValue.zeros_same_value_distinct_bits
#print axioms Algal.Core.NumericInjectivity.units_same_exponent_lt
#print axioms Algal.Core.NumericInjectivity.units_earlier_exponent_lt
#print axioms Algal.Core.NumericInjectivity.units_injective
#print axioms Algal.Core.NumericInjectivity.bitUnits_coefficient
#print axioms Algal.Core.NumericInjectivity.precision_shift
#print axioms Algal.Core.NumericInjectivity.signedUnits_shift
#print axioms Algal.Core.NumericInjectivity.exact_fixed_precision
#print axioms Algal.Core.NumericInjectivity.fixed_precision_injective
#print axioms Algal.Core.NumericInjectivity.exact_equal_signedUnits
#print axioms Algal.Core.NumericInjectivity.sign_apply_natAbs
#print axioms Algal.Core.NumericInjectivity.exact_equal_bitUnits
#print axioms Algal.Core.NumericInjectivity.bitUnits_equal_fields
#print axioms Algal.Core.NumericInjectivity.sign_equal_signBit
#print axioms Algal.Core.NumericInjectivity.bits_equal_of_units_sign
#print axioms Algal.Core.NumericInjectivity.zero_units_exact_zero
#print axioms Algal.Core.NumericInjectivity.zero_pair_normalizes
#print axioms Algal.Core.NumericInjectivity.exact_equal_normalizes
#print axioms Algal.Core.NumericInjectivity.denote_equal_iff_equivalent
#print axioms Algal.Core.NumericInjectivity.rational_equal_iff_equivalent
#print axioms Algal.Core.NumericInjectivity.normalized_denotation_injective
#print axioms Algal.Core.NumericInjectivity.signed_zero_equivalence_admitted
#print axioms Algal.Core.NumericInjectivity.distinct_one_two_denotation_rejected
#print axioms Algal.Core.RoundingInterval.value_fixed_units
#print axioms Algal.Core.RoundingInterval.positive_code_units_lt
#print axioms Algal.Core.RoundingInterval.positive_code_value_lt
#print axioms Algal.Core.RoundingInterval.positive_code_value_le_iff
#print axioms Algal.Core.RoundingInterval.adjacent_values_lt
#print axioms Algal.Core.RoundingInterval.adjacent_no_intermediate
#print axioms Algal.Core.RoundingInterval.midpoint_between
#print axioms Algal.Core.RoundingInterval.midpoint_left_distance
#print axioms Algal.Core.RoundingInterval.midpoint_right_distance
#print axioms Algal.Core.RoundingInterval.midpoint_left_strict
#print axioms Algal.Core.RoundingInterval.midpoint_right_strict
#print axioms Algal.Core.RoundingInterval.midpoint_equal_distances
#print axioms Algal.Core.RoundingInterval.coefficient_parity
#print axioms Algal.Core.RoundingInterval.adjacent_even_toggle
#print axioms Algal.Core.RoundingInterval.model_tie_keeps_even
#print axioms Algal.Core.RoundingInterval.model_tie_moves_odd
#print axioms Algal.Core.RoundingInterval.cell_neighbor_nearest
#print axioms Algal.Core.RoundingInterval.odd_cell_neighbor_strict
#print axioms Algal.Core.RoundingInterval.cell_midpoint_bounds
#print axioms Algal.Core.RoundingInterval.distance_outside_left
#print axioms Algal.Core.RoundingInterval.distance_outside_right
#print axioms Algal.Core.RoundingInterval.cell_global_nearest_nonnegative
#print axioms Algal.Core.RoundingInterval.odd_cell_global_strict_nonnegative
#print axioms Algal.Core.RoundingInterval.center_in_own_cell
#print axioms Algal.Core.RoundingInterval.one_left_adjacent
#print axioms Algal.Core.RoundingInterval.one_right_adjacent
#print axioms Algal.Core.RoundingInterval.after_one_right_adjacent
#print axioms Algal.Core.RoundingInterval.one_even
#print axioms Algal.Core.RoundingInterval.after_one_odd
#print axioms Algal.Core.RoundingInterval.one_actual_value
#print axioms Algal.Core.RoundingInterval.one_self_in_cell
#print axioms Algal.Core.RoundingInterval.one_lower_midpoint_included
#print axioms Algal.Core.RoundingInterval.odd_lower_midpoint_rejected
#print axioms Algal.Core.RoundingInterval.one_neighbor_gaps_asymmetric
#print axioms Algal.Core.RoundingInterval.subnormal_normal_adjacent
#print axioms Algal.Core.RoundingInterval.minimum_normal_next_adjacent
#print axioms Algal.Core.RoundingInterval.minimum_normal_even
#print axioms Algal.Core.RoundingInterval.subnormal_normal_gaps_equal
#print axioms Algal.Core.DecimalSyntax.readDigit_char
#print axioms Algal.Core.DecimalSyntax.char_readDigit
#print axioms Algal.Core.DecimalSyntax.takeDigits_stopped
#print axioms Algal.Core.DecimalSyntax.takeDigits_render
#print axioms Algal.Core.DecimalSyntax.takeDigits_reconstruct
#print axioms Algal.Core.DecimalSyntax.takeDigits_remainder_stopped
#print axioms Algal.Core.DecimalSyntax.readDigits_render
#print axioms Algal.Core.DecimalSyntax.readInteger_render
#print axioms Algal.Core.DecimalSyntax.terminal_stopped
#print axioms Algal.Core.DecimalSyntax.digit_ne_marker
#print axioms Algal.Core.DecimalSyntax.readExponentSign_digit
#print axioms Algal.Core.DecimalSyntax.readExponentSign_render
#print axioms Algal.Core.DecimalSyntax.readExponentTail_render
#print axioms Algal.Core.DecimalSyntax.readExponent_terminal
#print axioms Algal.Core.DecimalSyntax.readExponent_render
#print axioms Algal.Core.DecimalSyntax.exponentChars_stopped
#print axioms Algal.Core.DecimalSyntax.readFraction_exponent
#print axioms Algal.Core.DecimalSyntax.readFraction_render
#print axioms Algal.Core.DecimalSyntax.fractionChars_stopped
#print axioms Algal.Core.DecimalSyntax.readUnsigned_render
#print axioms Algal.Core.DecimalSyntax.readPrefix_unsigned
#print axioms Algal.Core.DecimalSyntax.readPrefix_render
#print axioms Algal.Core.DecimalSyntax.readWhole_render
#print axioms Algal.Core.DecimalSyntax.render_injective
#print axioms Algal.Core.DecimalSyntax.readDigits_sound
#print axioms Algal.Core.DecimalSyntax.readInteger_sound
#print axioms Algal.Core.DecimalSyntax.readExponentSign_sound
#print axioms Algal.Core.DecimalSyntax.readExponentTail_sound
#print axioms Algal.Core.DecimalSyntax.readExponent_sound
#print axioms Algal.Core.DecimalSyntax.readFraction_sound
#print axioms Algal.Core.DecimalSyntax.readUnsigned_sound
#print axioms Algal.Core.DecimalSyntax.readPrefix_sound
#print axioms Algal.Core.DecimalSyntax.readWhole_sound
#print axioms Algal.Core.DecimalSyntax.readWhole_iff
#print axioms Algal.Core.DecimalSyntax.digitsValue_append
#print axioms Algal.Core.DecimalSyntax.coefficient_decomposition
#print axioms Algal.Core.DecimalSyntax.digitsValue_bound
#print axioms Algal.Core.DecimalSyntax.scale_rational
#print axioms Algal.Core.DecimalSyntax.denote_rational
#print axioms Algal.Core.DecimalSyntax.denominator_positive
#print axioms Algal.Core.DecimalSyntax.denote_roundtrip
#print axioms Algal.Core.DecimalSyntax.tenth_lexeme
#print axioms Algal.Core.DecimalSyntax.tenth_parse
#print axioms Algal.Core.DecimalSyntax.tenth_exact_value
#print axioms Algal.Core.DecimalSyntax.signed_zeros_same_rational
#print axioms Algal.Core.DecimalSyntax.signed_zeros_distinct_syntax
#print axioms Algal.Core.DecimalSyntax.decimal_tenth_not_exact_binary64_tenth
#print axioms Algal.Core.DecimalSyntax.reject_empty
#print axioms Algal.Core.DecimalSyntax.reject_leading_plus
#print axioms Algal.Core.DecimalSyntax.reject_leading_zero
#print axioms Algal.Core.DecimalSyntax.reject_negative_leading_zero
#print axioms Algal.Core.DecimalSyntax.reject_empty_fraction
#print axioms Algal.Core.DecimalSyntax.reject_empty_exponent
#print axioms Algal.Core.DecimalSyntax.reject_empty_signed_exponent
#print axioms Algal.Core.DecimalSyntax.reject_nan
#print axioms Algal.Core.DecimalSyntax.reject_infinity
#print axioms Algal.Core.DecimalSyntax.reject_hexadecimal
#print axioms Algal.Core.DecimalSyntax.reject_fullwidth_digits
#print axioms Algal.Core.DecimalSyntax.reject_trailing_junk
#print axioms Algal.Core.DecimalSyntax.enormous_exponent_syntax_admitted
#print axioms Algal.Core.DecimalSyntax.negative_exponent_syntax_admitted
#print axioms Algal.Core.Text.scalar_range
#print axioms Algal.Core.Text.utf16Char_length
#print axioms Algal.Core.Text.utf16Char_unit_bound
#print axioms Algal.Core.Text.decodeChar_utf16Char
#print axioms Algal.Core.Text.utf16Char_injective
#print axioms Algal.Core.Text.decodeChars_utf16
#print axioms Algal.Core.Text.utf16_injective
#print axioms Algal.Core.Text.insertKey_preserves_keys
#print axioms Algal.Core.Text.canonicalKeys_preserves_keys
#print axioms Algal.Core.Text.scalar_surrogate_rejected
#print axioms Algal.Core.Text.utf16_supplementary_witness
#print axioms Algal.Core.Text.no_nfc_identification
#print axioms Algal.Core.Text.scalar_order_is_not_utf16_order
#print axioms Algal.Core.Text.index_maximum_admitted
#print axioms Algal.Core.Text.index_overflow_rejected
#print axioms Algal.Core.Text.index_leading_zero_rejected
#print axioms Algal.Core.Text.index_plus_rejected
#print axioms Algal.Core.Text.index_negative_zero_rejected
#print axioms Algal.Core.Text.canonical_key_order_witness
#print axioms Algal.Core.JsonString.hexControl_roundtrip
#print axioms Algal.Core.JsonString.readUnit_escapeChar
#print axioms Algal.Core.JsonString.escapeChar_head
#print axioms Algal.Core.JsonString.scan_escapeChar
#print axioms Algal.Core.JsonString.scan_escapedBody
#print axioms Algal.Core.JsonString.escapeChar_length
#print axioms Algal.Core.JsonString.escapedBody_length
#print axioms Algal.Core.JsonString.readQuoted_quote_suffix
#print axioms Algal.Core.JsonString.fromUTF8_toUTF8
#print axioms Algal.Core.JsonString.quoteBytes_utf8
#print axioms Algal.Core.JsonString.quotedBytes_roundtrip
#print axioms Algal.Core.JsonString.quotedBytes_injective
#print axioms Algal.Core.JsonString.decodeBytes_roundtrip
#print axioms Algal.Core.JsonString.standard_controls_witness
#print axioms Algal.Core.JsonString.supplementary_utf8_witness
#print axioms Algal.Core.JsonString.malformed_utf8_rejected
#print axioms Algal.Core.JsonString.overlong_utf8_rejected
#print axioms Algal.Core.JsonString.surrogate_utf8_rejected
#print axioms Algal.Core.JsonString.leading_bom_rejected
#print axioms Algal.Core.JsonString.embedded_bom_retained
#print axioms Algal.Core.JsonString.literal_control_rejected
#print axioms Algal.Core.JsonString.escaped_quote_is_content
#print axioms Algal.Core.JsonString.trailing_content_rejected
#print axioms Algal.Core.JsonString.missing_end_quote_rejected
#print axioms Algal.Core.JsonString.invalid_escape_rejected
#print axioms Algal.Core.ByteFraming.readBytes_quote_suffix
#print axioms Algal.Core.ByteFraming.quoted_prefix_framing
#print axioms Algal.Core.ByteFraming.quoted_prefix_framing_iff
#print axioms Algal.Core.ByteFraming.embedded_delimiters_and_suffix
#print axioms Algal.Core.ByteFraming.distinct_prefix_splice_rejected
#print axioms Algal.Core.OwnMap.lookup_write_same
#print axioms Algal.Core.OwnMap.lookup_write_other
#print axioms Algal.Core.OwnMap.overwrite_last_wins
#print axioms Algal.Core.OwnMap.distinct_writes_commute
#print axioms Algal.Core.OwnMap.lookup_defined_only_if_declared
#print axioms Algal.Core.OwnMap.lookup_absent_if_undeclared
#print axioms Algal.Core.OwnMap.parsed_duplicate_witness
#print axioms Algal.Core.OwnMap.insertion_order_witness
#print axioms Algal.Core.OwnMap.inherited_name_absent
#print axioms Algal.Core.OwnMap.proto_name_is_an_own_key
#print axioms Algal.Core.OwnMap.absent_is_not_present_none
#print axioms Algal.Core.KeyOrder.digit_char_rebuild
#print axioms Algal.Core.KeyOrder.parseDigits_append_repr
#print axioms Algal.Core.KeyOrder.parseDigits_nonzero_head
#print axioms Algal.Core.KeyOrder.arrayIndex_digits
#print axioms Algal.Core.KeyOrder.arrayIndex_injective
#print axioms Algal.Core.KeyOrder.keyOrder_swap
#print axioms Algal.Core.KeyOrder.keyLE_trans
#print axioms Algal.Core.KeyOrder.keyLE_antisymm
#print axioms Algal.Core.KeyOrder.keyLE_total
#print axioms Algal.Core.KeyOrder.keyOrder_notGT
#print axioms Algal.Core.KeyOrder.insertKey_sorted
#print axioms Algal.Core.KeyOrder.canonicalKeys_sorted
#print axioms Algal.Core.KeyOrder.canonicalKeys_permutation_invariant
#print axioms Algal.Core.KeyOrder.canonicalKeys_idempotent
#print axioms Algal.Core.KeyOrder.lookup_isSome_iff
#print axioms Algal.Core.KeyOrder.eraseDups_nodup
#print axioms Algal.Core.KeyOrder.support_permutation_of_equivalent
#print axioms Algal.Core.KeyOrder.canonicalProjection_eq_of_equivalent
#print axioms Algal.Core.KeyOrder.lookup_keyed_map
#print axioms Algal.Core.KeyOrder.canonicalProjection_lookup
#print axioms Algal.Core.KeyOrder.canonicalProjection_eq_iff
#print axioms Algal.Core.KeyOrder.canonicalProjection_distinct_writes_commute
#print axioms Algal.Core.KeyOrder.changed_duplicate_winner_changes_projection
#print axioms Algal.Core.KeyOrder.reordered_map_witness
#print axioms Algal.Core.Json.normalizeNumbers_idempotent
#print axioms Algal.Core.Json.normalizeItems_idempotent
#print axioms Algal.Core.Json.normalizeFields_idempotent
#print axioms Algal.Core.Json.execute_append
#print axioms Algal.Core.Json.execute_encode
#print axioms Algal.Core.Json.execute_encodeItems
#print axioms Algal.Core.Json.execute_encodeFields
#print axioms Algal.Core.Json.structural_roundtrip
#print axioms Algal.Core.Json.structural_encoding_injective
#print axioms Algal.Core.Json.structural_roundtrip_modulo_number_normalization
#print axioms Algal.Core.Json.normalized_structural_encoding_eq_iff
#print axioms Algal.Core.Json.malformed_stack_rejected
#print axioms Algal.Core.Json.nonfinite_token_rejected
#print axioms Algal.Core.Json.extra_value_rejected
#print axioms Algal.Core.Json.array_order_is_significant
#print axioms Algal.Core.Json.nested_structural_witness
#print axioms Algal.Core.Normalize.fieldsToList_ofList
#print axioms Algal.Core.Normalize.fieldsOfList_toList
#print axioms Algal.Core.Normalize.lookup_append
#print axioms Algal.Core.Normalize.lookupFields_cons
#print axioms Algal.Core.Normalize.lookup_map
#print axioms Algal.Core.Normalize.canonicalEntries_lookup
#print axioms Algal.Core.Normalize.canonicalEntries_eq_of_equivalent
#print axioms Algal.Core.Normalize.canonicalEntries_fallback_irrelevant
#print axioms Algal.Core.Normalize.canonicalEntries_keys
#print axioms Algal.Core.Normalize.canonicalEntries_nodup
#print axioms Algal.Core.Normalize.canonicalEntries_sorted
#print axioms Algal.Core.Normalize.lookup_reverse_unique
#print axioms Algal.Core.Normalize.canonicalFields_lookup
#print axioms Algal.Core.Normalize.canonicalFields_eq_of_lookup
#print axioms Algal.Core.Normalize.canonicalFields_nodup
#print axioms Algal.Core.Normalize.canonicalFields_sorted
#print axioms Algal.Core.Normalize.normalizeItems_toList
#print axioms Algal.Core.Normalize.normalizeItems_length
#print axioms Algal.Core.Normalize.normalizeFieldValues_lookup
#print axioms Algal.Core.Normalize.normalize_object_lookup
#print axioms Algal.Core.Normalize.numberEquivalent_iff_normalize
#print axioms Algal.Core.Normalize.equivalent_normalize
#print axioms Algal.Core.Normalize.equivalent_symm
#print axioms Algal.Core.Normalize.equivalent_trans
#print axioms Algal.Core.Normalize.normalize_sound
#print axioms Algal.Core.Normalize.normalizeItems_sound
#print axioms Algal.Core.Normalize.normalizeFieldValues_sound
#print axioms Algal.Core.Normalize.normalize_idempotent
#print axioms Algal.Core.Normalize.equivalent_iff_normalize_eq
#print axioms Algal.Core.Normalize.equivalent_refl
#print axioms Algal.Core.Normalize.canonicalTokens_roundtrip
#print axioms Algal.Core.Normalize.canonicalTokens_eq_iff
#print axioms Algal.Core.Normalize.canonicalTokens_normalize
#print axioms Algal.Core.Normalize.decoded_canonicalTokens_equivalent
#print axioms Algal.Core.Normalize.canonicalTokens_injective_on_normalized
#print axioms Algal.Core.Normalize.nested_normalization_witness
#print axioms Algal.Core.Normalize.nested_equivalence_witness
#print axioms Algal.Core.Normalize.signed_zero_normalization_witness
#print axioms Algal.Core.Normalize.overwritten_duplicate_ignored
#print axioms Algal.Core.Normalize.reordered_distinct_keys_witness
#print axioms Algal.Core.Normalize.changed_duplicate_winner_rejected
#print axioms Algal.Core.Normalize.array_permutation_rejected
#print axioms Algal.Core.Normalize.absent_and_present_null_rejected
#print axioms Algal.Core.Normalize.inherited_name_stays_absent
#print axioms Algal.Core.Normalize.proto_is_retained_own_key
#print axioms Algal.Core.Normalize.unicode_normalization_not_applied
#print axioms Algal.Core.JsonLayout.numericHead_not_close
#print axioms Algal.Core.JsonLayout.render_not_close
#print axioms Algal.Core.JsonLayout.read_render
#print axioms Algal.Core.JsonLayout.read_renderItems
#print axioms Algal.Core.JsonLayout.read_renderFields
#print axioms Algal.Core.JsonLayout.number_render_nonempty
#print axioms Algal.Core.JsonLayout.weight_positive
#print axioms Algal.Core.JsonLayout.weight_le_render
#print axioms Algal.Core.JsonLayout.weightItems_le_render
#print axioms Algal.Core.JsonLayout.weightFields_le_render
#print axioms Algal.Core.JsonLayout.whole_roundtrip
#print axioms Algal.Core.JsonLayout.bytes_roundtrip
#print axioms Algal.Core.JsonLayout.bytes_equal_implies_normalized
#print axioms Algal.Core.JsonLayout.bytes_to_tokens
#print axioms Algal.Core.JsonLayout.bytes_to_structural_decoder
#print axioms Algal.Core.JsonLayout.noNumberLaws
#print axioms Algal.Core.JsonLayout.noNumbers_normalized
#print axioms Algal.Core.JsonLayout.noNumberItems_normalized
#print axioms Algal.Core.JsonLayout.noNumberFields_normalized
#print axioms Algal.Core.JsonLayout.noNumbers_bytes_roundtrip
#print axioms Algal.Core.JsonLayout.noNumbers_bytes_injective
#print axioms Algal.Core.JsonLayout.nestedStringTree_no_numbers
#print axioms Algal.Core.JsonLayout.nested_number_free_bytes_roundtrip
#print axioms Algal.Core.JsonLayout.numeric_stub_has_no_full_laws
#print axioms Algal.Core.JsonLayout.bytes_of_chars
#print axioms Algal.Core.JsonLayout.array_trailing_comma_rejected
#print axioms Algal.Core.JsonLayout.object_trailing_comma_rejected
#print axioms Algal.Core.JsonLayout.mismatched_delimiter_rejected
#print axioms Algal.Core.JsonLayout.missing_colon_rejected
#print axioms Algal.Core.JsonLayout.extra_root_rejected
#print axioms Algal.Core.JsonLayout.number_branch_stub_rejected
#print axioms Algal.Core.JsonLayout.normalizeNumbers_lookup
#print axioms Algal.Core.JsonLayout.numberNormalization_sound
#print axioms Algal.Core.JsonLayout.numberNormalizationItems_sound
#print axioms Algal.Core.JsonLayout.numberNormalizationFields_sound
#print axioms Algal.Core.JsonLayout.normalize_after_numberNormalization
#print axioms Algal.Core.JsonLayout.canonicalBytes_roundtrip
#print axioms Algal.Core.JsonLayout.canonicalBytes_eq_iff
#print axioms Algal.Core.JsonLayout.canonicalBytes_to_tokens
#print axioms Algal.Core.JsonLayout.noNumbers_canonicalBytes_roundtrip
#print axioms Algal.Core.JsonLayout.noNumbers_canonicalBytes_eq_iff
#print axioms Algal.Core.JsonLayout.noNumberFields_lookup
#print axioms Algal.Core.JsonLayout.noNumberFields_ofList
#print axioms Algal.Core.JsonLayout.noNumberFields_canonical
#print axioms Algal.Core.JsonLayout.noNumbers_normalize
#print axioms Algal.Core.JsonLayout.noNumberItems_normalize
#print axioms Algal.Core.JsonLayout.noNumberFields_normalize
#print axioms Algal.Core.JsonLayout.numberFree_canonical_roundtrip
#print axioms Algal.Core.JsonLayout.numberFree_canonical_eq_iff
#print axioms Algal.Core.JsonLayout.nested_number_free_canonical_roundtrip
#print axioms Algal.Core.Ports.capability_no_json_widening
#print axioms Algal.Core.Ports.capability_class_preserved
#print axioms Algal.Core.Ports.reference_is_not_payload
#print axioms Algal.Core.Ports.many_to_scalar_nonjson_rejected
#print axioms Algal.Core.Ports.accepted_value_byte_bound
#print axioms Algal.Core.Ports.accepted_scalar_capability_class
#print axioms Algal.Core.Ports.accepted_many_is_array
#print axioms Algal.Core.Ports.checked_assignment_preserves_types
#print axioms Algal.Core.Ports.undeclared_assignment_rejected
#print axioms Algal.Core.Ports.signature_does_not_imply_schema_satisfaction
#print axioms Algal.Core.Ports.open_choice_does_not_imply_label_satisfaction
#print axioms Algal.Core.Ports.many_to_json_witness
#print axioms Algal.Core.Ports.capability_syntax_witness
#print axioms Algal.Core.Ports.capability_wrong_class_rejected
#print axioms Algal.Core.Ports.empty_digest_rejected
#print axioms Algal.Core.Ports.inherited_port_rejected
#print axioms Algal.Core.Ports.syntax_does_not_mint_authority
#print axioms Algal.Core.Graph.accepted_edge_resolves_own_ports
#print axioms Algal.Core.Graph.ownOutput_is_declared
#print axioms Algal.Core.Graph.ownInput_is_declared
#print axioms Algal.Core.Graph.interfaceInput_is_declared_input_cell
#print axioms Algal.Core.Graph.accepted_interface_input_resolves
#print axioms Algal.Core.Graph.accepted_interface_output_resolves
#print axioms Algal.Core.Graph.accepted_edge_increases_rank
#print axioms Algal.Core.Graph.accepted_path_increases_rank
#print axioms Algal.Core.Graph.accepted_graph_acyclic
#print axioms Algal.Core.Graph.accepted_scalar_cardinality
#print axioms Algal.Core.Graph.accepted_no_mixed_failure_inputs
#print axioms Algal.Core.Graph.accepted_normal_capability_edge_preserves_class
#print axioms Algal.Core.Graph.accepted_child_output_corresponds
#print axioms Algal.Core.Graph.accepted_child_input_corresponds
#print axioms Algal.Core.Graph.declared_acyclic_graph_admitted
#print axioms Algal.Core.Graph.duplicate_scalar_edge_rejected
#print axioms Algal.Core.Graph.inherited_endpoint_rejected
#print axioms Algal.Core.Graph.self_cycle_rejected
#print axioms Algal.Core.Graph.missing_child_port_rejected
#print axioms Algal.Core.Graph.exact_child_interface_admitted
#print axioms Algal.Core.Accounting.preIncrement_success_bound
#print axioms Algal.Core.Accounting.preIncrement_at_limit_rejected
#print axioms Algal.Core.Accounting.preIncrement_below_limit_admitted
#print axioms Algal.Core.Accounting.postCharge_monotone
#print axioms Algal.Core.Accounting.postCharge_envelope
#print axioms Algal.Core.Accounting.postCharge_success_bound
#print axioms Algal.Core.Accounting.postCharge_failure_retains_charge
#print axioms Algal.Core.Accounting.strict_limit_is_not_an_invariant
#print axioms Algal.Core.Accounting.callback_failure_keeps_cost
#print axioms Algal.Core.Accounting.direct_tool_failure_no_success_charge
#print axioms Algal.Core.Accounting.effect_attempt_base_bound
#print axioms Algal.Core.Accounting.charged_group_envelope
#print axioms Algal.Core.Accounting.uint64_add_without_wrap
#print axioms Algal.Core.Accounting.exact_integer_envelope_fits_uint64
#print axioms Algal.Core.Accounting.admitted_cost_nonnegative
#print axioms Algal.Core.Accounting.negative_callback_cost_rejected
#print axioms Algal.Core.Accounting.excessive_callback_cost_rejected
#print axioms Algal.Core.Accounting.zero_callback_cost_admitted
#print axioms Algal.Core.Accounting.typical_callback_cost_admitted
#print axioms Algal.Core.Oracle.successful_replay_binds_head
#print axioms Algal.Core.Oracle.successful_replay_consumes_exactly_one
#print axioms Algal.Core.Oracle.changed_occurrence_rejected
#print axioms Algal.Core.Oracle.changed_request_rejected
#print axioms Algal.Core.Oracle.replay_deterministic
#print axioms Algal.Core.Oracle.successful_replay_witness
#print axioms Algal.Core.Oracle.same_request_different_occurrence_is_not_replay
#print axioms Algal.Core.Oracle.external_failure_is_replayable
#print axioms Algal.Core.Oracle.reordered_tape_rejected
