/** Lane-local coverage for the differential driver: catalog hygiene, the
 * independent JSON/canonical/oracle mirrors, verdict classification, the
 * bounded shrinker, worker manifest admission, and an in-process wasm leg
 * against the committed artifact. The registered suite's subprocess mode and
 * native leg are exercised by runDifferential itself; tests here pin the
 * deterministic parts. */

import { expect, test } from "bun:test";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { catalog } from "./cases";
import { BOUNDS, canonical, canonicalBytes, countNodes, keyOrder, valueBytes, valueDepth, Bounds } from "./canonical";
import { parseJsonBytes, JSON_CONTAINER_DEPTH_MAX, type JVal } from "./json";
import { predictEval, predictCheck, runMirror } from "./oracle";
import { classifyResponse, compareCase, wrapperFaithful } from "./engine";
import { candidates, shrinkBytes } from "./shrink";
import { runWorkerManifest } from "./worker";
import { callRaw, loadWasmModule } from "./wasm";
import { differentialProfile, admitReport, DEFAULT_SEEDS } from "./adapter";
import { runDifferential, LIMITS, type Report } from "./run";

const enc = new TextEncoder();
const num = (v: number): JVal => ({ kind: "num", f64: v, u64: Number.isSafeInteger(v) && v >= 0 ? BigInt(v) : null });
const WASM = join(import.meta.dir, "../../src/algal_expr.wasm");
const NATIVE = process.env.ALGAL_DIFFERENTIAL_NATIVE_BIN;

// ------------------------------------------------------------ catalog -----

test("catalog is deterministic, uniquely identified, bounded and modal", () => {
  const a = catalog(DEFAULT_SEEDS), b = catalog(DEFAULT_SEEDS);
  expect(a.length).toBe(b.length);
  expect(a.map(c => c.id)).toEqual(b.map(c => c.id));
  for (let i = 0; i < a.length; i++) expect(Buffer.from(a[i]!.bytes).toString("base64")).toBe(Buffer.from(b[i]!.bytes).toString("base64"));
  expect(new Set(a.map(c => c.id)).size).toBe(a.length);
  expect(a.length).toBeGreaterThan(300);
  expect(a.length).toBeLessThanOrEqual(LIMITS.cases);
  for (const c of a) {
    expect(c.bytes.byteLength).toBeLessThanOrEqual(LIMITS.inputBytes);
    expect(c.mode === "eval" || c.mode === "check").toBe(true);
    expect(/^[a-z0-9._-]+$/i.test(c.id)).toBe(true); // worker filename admission
  }
  expect(a.filter(c => c.mode === "check").length).toBeGreaterThan(15);
  expect(a.filter(c => c.id.startsWith("gen-")).length).toBe(4 * 60);
  expect(a.filter(c => c.wrapper).length).toBeGreaterThan(50);
  // Different seed streams produce different generated bytes.
  const alt = catalog([0xdead]);
  expect(alt.some(c => c.id.startsWith("gen-dead-"))).toBe(true);
});

// ------------------------------------------------------------- json.rs ----

test("independent parser: byte admission edges", () => {
  expect(parseJsonBytes(enc.encode("")).ok).toBe(false);
  expect(parseJsonBytes(enc.encode("  \t\n\r ")).ok).toBe(false);
  expect(parseJsonBytes(enc.encode("null")).ok).toBe(true);
  expect(parseJsonBytes(enc.encode("null ")).ok).toBe(true);
  expect(parseJsonBytes(enc.encode("null x")).ok).toBe(false);
  expect(parseJsonBytes(enc.encode("﻿null")).ok).toBe(false); // BOM rejects
  expect(parseJsonBytes(enc.encode('{"a":1,"a":2}')).ok).toBe(true);
  const dup = parseJsonBytes(enc.encode('{"a":1,"a":2}'));
  expect(dup.ok && dup.value instanceof Map && dup.value.get("a")).toEqual({ kind: "num", f64: 2, u64: 2n });
  // Invalid UTF-8 and lone surrogates reject; valid astral pairs admit.
  expect(parseJsonBytes(Uint8Array.from([0x22, 0xed, 0xa0, 0x80, 0x22])).ok).toBe(false);
  expect(parseJsonBytes(Uint8Array.from([0x22, 0x80, 0x22])).ok).toBe(false);
  expect(parseJsonBytes(enc.encode('"\\ud800"')).ok).toBe(false);
  expect(parseJsonBytes(enc.encode('"\\udc00"')).ok).toBe(false);
  expect(parseJsonBytes(enc.encode('"\\ud83d\\ude00"')).ok).toBe(true);
  expect(parseJsonBytes(enc.encode('"\\ud800\\ud800"')).ok).toBe(false);
  expect(parseJsonBytes(Uint8Array.from([0x22, 0x00, 0x22])).ok).toBe(false); // raw control
  expect(parseJsonBytes(Uint8Array.from([0x22, 0x7f, 0x22])).ok).toBe(true);  // DEL is data
});

test("independent parser: number domain boundaries", () => {
  const numAt = (t: string): JVal => {
    const r = parseJsonBytes(enc.encode(t));
    if (!r.ok) throw r.error;
    return r.value;
  };
  expect(numAt("18446744073709551615")).toEqual({ kind: "num", f64: Number("18446744073709551615"), u64: 18446744073709551615n });
  expect((numAt("18446744073709551616") as { u64: bigint | null }).u64).toBe(null); // falls back to f64
  expect((numAt("-9223372036854775808") as { f64: number }).f64).toBe(-(2 ** 63));
  expect(numAt("5e-324")).toEqual({ kind: "num", f64: 5e-324, u64: null });
  expect(parseJsonBytes(enc.encode("1e309")).ok).toBe(false);   // non-finite rejects
  expect(parseJsonBytes(enc.encode("01")).ok).toBe(false);
  expect(parseJsonBytes(enc.encode("+1")).ok).toBe(false);
  expect(parseJsonBytes(enc.encode("1.")).ok).toBe(false);
  expect(numAt("1e2")).toEqual({ kind: "num", f64: 100, u64: null }); // exponent spelling is f64-typed
  const neg0 = numAt("-0") as { f64: number; u64: bigint | null };
  expect(Object.is(neg0.f64, -0)).toBe(true);
});

test("independent parser: container depth boundary 127/128", () => {
  const deep = (n: number) => enc.encode("[".repeat(n) + "1" + "]".repeat(n));
  expect(parseJsonBytes(deep(JSON_CONTAINER_DEPTH_MAX)).ok).toBe(true);
  expect(parseJsonBytes(deep(JSON_CONTAINER_DEPTH_MAX + 1)).ok).toBe(false);
});

// --------------------------------------------------------- canonical ------

test("canonical key order: array indices numerically first, then UTF-16 units", () => {
  const m = new Map<string, JVal>();
  for (const k of ["z", "10", "￿", "𐀀", "2", "01", "4294967296", "4294967295", "4294967294", "a", "A", "0"]) m.set(k, num(0));
  const text = canonical(m);
  const order = [...text.matchAll(/"((?:[^"\\]|\\.)*)":/g)].map(x => JSON.parse(`"${x[1]}"`));
  // Index keys (u32, canonical spelling, < 2^32-1) numerically first — note
  // 4294967295 is u32::MAX and is NOT an index key. Remaining keys sort by
  // UTF-16 code units, where 𐀀 (U+10000 → D800 DC00) precedes ￿ (U+FFFF) —
  // the opposite of UTF-8/scalar order. Both facts are pinned deliberately.
  expect(order).toEqual(["0", "2", "10", "4294967294", "01", "4294967295", "4294967296", "A", "a", "z", "𐀀", "￿"]);
  expect(keyOrder("2", "10")).toBeLessThan(0);
  expect(keyOrder("4294967294", "01")).toBeLessThan(0); // 4294967294 is a u32 index; "01" is not
  expect(keyOrder("4294967295", "0")).toBeGreaterThan(0); // u32::MAX sorts as a plain string
  expect(keyOrder("𐀀", "￿")).toBeLessThan(0); // UTF-16 units; scalar order disagrees
});

test("structural mirrors: node count, depth and canonical byte accounting", () => {
  const v: JVal = new Map<string, JVal>([["b", [num(1), num(2)]], ["a", num(0)]]);
  expect(countNodes(v)).toBe(5);
  expect(valueDepth(v)).toBe(2);
  expect(canonical(v)).toBe('{"a":0,"b":[1,2]}');
  expect(canonicalBytes(v)).toBe(17);
  expect(() => valueBytes(Array.from({ length: BOUNDS.maxListLen + 1 }, () => num(0)), 0)).toThrow(Bounds);
  let deep: JVal = num(0);
  for (let i = 0; i < BOUNDS.maxValueDepth + 1; i++) deep = [deep];
  expect(() => valueBytes(deep, 0)).toThrow(Bounds);
  expect(() => valueBytes("x".repeat(BOUNDS.maxStringBytes + 1), 0)).toThrow(Bounds);
});

// -------------------------------------------------------------- oracle ----

test("oracle predicts full canonical response including spent fuel", () => {
  const r = predictEval(enc.encode('{"program":["add",1,2],"fuel":100}'));
  expect(r).toEqual({ ok: true, value: { kind: "num", f64: 3, u64: null }, fuel: 4 });
  const fuelErr = predictEval(enc.encode('{"program":["add",1,2],"fuel":3}'));
  expect(fuelErr).toEqual({ ok: false, code: "EXPR_FUEL", fuel: 3 });
  const parse = predictEval(enc.encode("not json"));
  expect(parse).toEqual({ ok: false, code: "EXPR_PARSE", fuel: 0 });
  const noProgram = predictEval(enc.encode('{"env":{"x":1}}'));
  expect(noProgram).toEqual({ ok: false, code: "EXPR_PARSE", fuel: 0 });
  // fuel spelling: u64 typed integers admit; float-typed or out-of-range reject as bounds.
  expect(predictEval(enc.encode('{"program":true,"fuel":5}'))).toEqual({ ok: true, value: true, fuel: 1 });
  expect(predictEval(enc.encode('{"program":true,"fuel":100.0}')).ok).toBe(false);
  expect(predictEval(enc.encode('{"program":true,"fuel":1000001}')).ok).toBe(false);
  expect(predictCheck(enc.encode('{"program":["get","x"],"names":["x"]}'))).toEqual({ ok: true });
  expect(predictCheck(enc.encode('{"program":["get","x"],"names":[]}'))).toEqual({ ok: false, code: "EXPR_PATH" });
});

test("runMirror bounds pipeline order: env limits precede program check", () => {
  const hugeEnv = new Map<string, JVal>();
  for (let i = 0; i < BOUNDS.maxObjectKeys + 1; i++) hugeEnv.set(`k${i}`, num(0));
  const r = runMirror(true, hugeEnv, 100);
  expect("err" in r && r.err instanceof Bounds && r.err.what === "object-keys").toBe(true);
});

// -------------------------------------------------------------- engine ----

const RESP_OK = '{"fuel":4,"ok":true,"value":3}';
const RESP_ERR = '{"err":{"code":"EXPR_FUEL","what":"fuel"},"fuel":3,"ok":false}';

test("classifyResponse separates ok/error/malformed response classes", () => {
  expect(classifyResponse("eval", RESP_OK)).toEqual({ cls: "ok:fuel=4", canonical: "3" });
  expect(classifyResponse("eval", RESP_ERR)).toEqual({ cls: "err:EXPR_FUEL:fuel=3", canonical: null });
  expect(classifyResponse("eval", "garbage").cls).toBe("malformed");
  expect(classifyResponse("eval", '{"ok":true,"value":1}').cls).toBe("malformed"); // missing fuel
  expect(classifyResponse("check", '{"ok":true}')).toEqual({ cls: "ok", canonical: null });
  expect(classifyResponse("check", '{"err":{"code":"EXPR_PATH"},"ok":false}')).toEqual({ cls: "err:EXPR_PATH", canonical: null });
  expect(classifyResponse("check", '{"ok":true,"extra":1}').cls).toBe("ok"); // extra detail fields are tolerated
});

test("compareCase verdicts: agreement, oracle divergence, target divergence, wrapper divergence, transport, infra", () => {
  const bytes = enc.encode('{"program":["add",1,2],"fuel":100}');
  const okResp = JSON.stringify({ fuel: 4, ok: true, value: 3 });
  expect(compareCase("eval", bytes, { status: "ok", text: okResp }, { status: "ok", text: okResp }, { fuel: 4, ok: true, value: 3 }).verdict).toBe("agree");
  // oracle divergence: wasm claims fuel 5 for a 4-cost program
  expect(compareCase("eval", bytes, { status: "ok", text: '{"fuel":5,"ok":true,"value":3}' }, null, "skipped").verdict).toBe("mismatch-oracle");
  // target divergence: native bytes differ from wasm bytes
  const target = compareCase("eval", bytes, { status: "ok", text: okResp }, { status: "ok", text: '{"fuel":4,"ok":true,"value":3.0}' }, "skipped");
  expect(target.verdict === "mismatch-targets" || target.verdict === "agree").toBe(true); // identical text would agree; different bytes must not
  expect(compareCase("eval", bytes, { status: "ok", text: okResp }, { status: "ok", text: RESP_ERR }, "skipped").verdict).toBe("mismatch-targets");
  // wrapper divergence: wrapper result differs from raw boundary object
  expect(compareCase("eval", bytes, { status: "ok", text: okResp }, null, { fuel: 4, ok: true, value: 4 }).verdict).toBe("mismatch-wrapper");
  // transport and infrastructure classes
  expect(compareCase("eval", bytes, { status: "null-input", error: "x" }, null, "skipped").verdict).toBe("wasm-transport");
  expect(compareCase("eval", bytes, { status: "trap", error: "x" }, null, "skipped").verdict).toBe("infra-failure");
  expect(compareCase("eval", bytes, { status: "ok", text: "not-json" }, null, "skipped").verdict).toBe("infra-failure");
  expect(compareCase("eval", bytes, { status: "ok", text: okResp }, { status: "timeout", error: "d" }, "skipped").verdict).toBe("infra-failure");
  // wrapper threw is recorded, not hidden
  const threw = compareCase("eval", bytes, { status: "ok", text: okResp }, null, { threw: "boom" });
  expect(threw.wrapperClass?.startsWith("wrapper-threw:")).toBe(true);
});

test("wrapperFaithful admits only envelopes whose fuel token survives JSON.stringify", () => {
  expect(wrapperFaithful(enc.encode('{"program":true}'))).toBe(true);
  expect(wrapperFaithful(enc.encode('{"program":true,"fuel":5}'))).toBe(true);
  expect(wrapperFaithful(enc.encode('{"program":true,"fuel":5.0}'))).toBe(false);  // 5.0 re-encodes as 5 — different admission
  expect(wrapperFaithful(enc.encode('{"program":true,"fuel":-1}'))).toBe(false);   // -1 loses its u64 refusal
  expect(wrapperFaithful(enc.encode('{"program":true,"fuel":"x"}'))).toBe(true);   // non-number fuel rejects identically
  expect(wrapperFaithful(enc.encode('not json'))).toBe(false);
});

// -------------------------------------------------------------- shrink ----

test("shrinkBytes reduces a reproducing input and reconfirms the result", async () => {
  const original = enc.encode('{"program":["add",["sub",5,["get","x"]],{"a":[1,2,3]}],"env":{"x":0}}');
  let calls = 0;
  const reproduces = async (c: Uint8Array): Promise<boolean> => {
    calls++;
    const p = parseJsonBytes(c);
    return p.ok && p.value instanceof Map && p.value.has("program");
  };
  const out = await shrinkBytes(original, reproduces, { attempts: 40, deadlineMs: 5000 });
  expect(out.bytes.byteLength).toBeLessThan(original.byteLength);
  expect(out.attempts).toBe(calls);
  expect(parseJsonBytes(out.bytes).ok).toBe(true);
});

test("shrinkBytes honors the attempt bound and refuses a non-reproducing seed", async () => {
  const original = enc.encode('{"program":["add",1,{"a":2},{"b":[3,4]}]}');
  let calls = 0;
  const out = await shrinkBytes(original, async () => { calls++; return false; }, { attempts: 7, deadlineMs: 5000 }).catch(e => e);
  // The seed itself does not reproduce — the loop must fail loudly, not return it.
  expect(String(out)).toContain("did not reproduce");
  const trimmed = await shrinkBytes(original, async c => { calls++; return c.byteLength > 20; }, { attempts: 100, deadlineMs: 5000 });
  expect(trimmed.bytes.byteLength).toBeGreaterThanOrEqual(21);
  expect(calls).toBeGreaterThan(0);
  const first = [...candidates(original)];
  expect(first.length).toBeGreaterThan(10);
  expect(first.every(c => c.byteLength <= original.byteLength)).toBe(true);
});

// -------------------------------------------------------------- wasm ------

test("committed wasm boundary answers a real envelope (in-process leg)", async () => {
  const mod = await loadWasmModule(WASM);
  const text = callRaw(mod, "algal_eval", enc.encode('{"program":["add",1,2],"fuel":100}'));
  expect(JSON.parse(text)).toEqual({ fuel: 4, ok: true, value: 3 });
  const chk = callRaw(mod, "algal_check", enc.encode('{"program":["get","x"],"names":["x"]}'));
  expect(JSON.parse(chk)).toEqual({ ok: true });
  // A trap/parse rejection is a shaped response, not a transport fault.
  const bad = callRaw(mod, "algal_eval", enc.encode("not json"));
  expect(JSON.parse(bad).ok).toBe(false);
});

test("worker manifest: per-case lines, zero-byte transport admission, read errors", async () => {
  const dir = await mkdtemp(join(tmpdir(), "diff-worker-"));
  await writeFile(join(dir, "a.bin"), enc.encode('{"program":true}'));
  await writeFile(join(dir, "b.bin"), enc.encode('{"program":["get","x"],"names":["x"]}'));
  await writeFile(join(dir, "empty.bin"), new Uint8Array(0));
  const manifestPath = join(dir, "m.json");
  await writeFile(manifestPath, JSON.stringify({
    wasm: WASM,
    cases: [
      { id: "a", path: join(dir, "a.bin"), mode: "eval", wrapper: true },
      { id: "b", path: join(dir, "b.bin"), mode: "check", wrapper: true },
      { id: "empty", path: join(dir, "empty.bin"), mode: "eval", wrapper: false },
      { id: "gone", path: join(dir, "gone.bin"), mode: "eval", wrapper: false },
    ],
  }));
  const lines = await runWorkerManifest(manifestPath);
  expect(lines).toHaveLength(4);
  expect(lines[0]).toMatchObject({ id: "a", wasm: { status: "ok" } });
  expect(lines[0]!.wrapper).toEqual({ fuel: 1, ok: true, value: true });
  expect(lines[1]).toMatchObject({ id: "b", wasm: { status: "ok" } });
  expect(lines[2]!.wasm.status).toBe("null-input");
  expect(lines[3]!.wasm.status).toBe("read-error");
});

// -------------------------------------------------------------- driver ----

test("inline differential run: all verdicts account for every case, oracle exact", async () => {
  const archiveDir = await mkdtemp(join(tmpdir(), "diff-run-"));
  const report = await runDifferential({
    root: join(import.meta.dir, "../.."),
    wasm: WASM,
    ...(NATIVE !== undefined ? { native: NATIVE } : {}),
    seeds: [1],
    archiveDir,
    mode: "inline",
  });
  expect(report.contract).toBe("algal.differential-report.v1");
  const total = Object.values(report.verdicts).reduce((a, b) => a + b, 0);
  expect(total).toBe(report.cases);
  expect(report.mismatches).toHaveLength(0);
  expect(report.oracle.exact).toBe(report.cases);
  expect(report.verdicts["infra-failure"]).toBeUndefined();
  expect(report.verdicts["mismatch-oracle"]).toBeUndefined();
  expect(report.verdicts["mismatch-targets"]).toBeUndefined();
  expect(report.coverage.ops.length).toBeGreaterThan(40);
  expect(report.artifacts.wasm.sha256).toMatch(/^sha256:[a-f0-9]{64}$/);
  admitReport(report as Report);
}, 120_000);

// -------------------------------------------------------------- adapter ---

test("profile selection: explicit absolute native path, bounded seed list", () => {
  for (const bad of [undefined, "", "relative/bin"]) {
    expect(() => differentialProfile(bad, undefined)).toThrow("explicit absolute");
  }
  expect(differentialProfile("/owned/native", undefined).seeds).toEqual([...DEFAULT_SEEDS]);
  expect(differentialProfile("/owned/native", "1,1831565813").seeds).toEqual([1, 0x6d2b79f5]);
  expect(() => differentialProfile("/owned/native", "")).toThrow();
  expect(() => differentialProfile("/owned/native", "-1")).toThrow();
  expect(() => differentialProfile("/owned/native", "4294967296")).toThrow();
  expect(() => differentialProfile("/owned/native", Array.from({ length: 17 }, () => "1").join(","))).toThrow("seed count bound");
});

test("admitReport rejects any failing verdict and requires full accounting", () => {
  const base: Report = {
    contract: "algal.differential-report.v1", seeds: [1], cases: 3, mode: "inline",
    artifacts: { wasm: { path: "/w", sha256: "sha256:" + "0".repeat(64), bytes: 1 }, native: null, bun: { path: "/b", sha256: "sha256:" + "0".repeat(64), bytes: 1 } },
    verdicts: { agree: 2, uncovered: 1 }, oracle: { exact: 3, uncovered: 0 },
    coverage: { ops: [], codes: {}, notes: [] }, mismatches: [], elapsedMs: 0,
  };
  expect(() => admitReport(base)).not.toThrow();
  expect(() => admitReport({ ...base, verdicts: { agree: 2 } })).toThrow("cover every case");
  expect(() => admitReport({ ...base, verdicts: { agree: 3, "infra-failure": 1 }, cases: 4 })).toThrow("failures or mismatches");
  expect(() => admitReport({ ...base, cases: 0 })).toThrow("case bound");
});
