import {mkdir,mkdtemp,opendir,lstat,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';
import {hashBytes,hashJson,readFileBounded,stableJson} from '../../lib/files';
import {CommandFailure,runCommand} from '../../lib/runner';
import {captureSpawnBinding,CONTRACT,RELATION} from './definition';
import {readmitArchive} from './readmit';
import {retainEvidence} from '../../lib/evidence-retention';
import {retainFailure} from '../../lib/failure';
import {actual,expected} from './adapter';import {fixtures} from './fixtures';import {canonical,execute,spawnDefinition,type Json} from './oracle';
import {admitInputs,admitNative,admitProjection,admitRaw,admitReplay,admitWorker,captureInputs,encoded,insist,LIMITS,readJson,Writer,type InputFile} from './custody';
const BASE=import.meta.dir;const ROOT=resolve(BASE,'../../..');
type File={path:string;bytes:number;sha256:string};
async function inventory(directory:string):Promise<File[]>{const files:File[]=[];let bytes=0,entries=0;async function walk(relative:string,depth:number){insist(depth<=8,'archive directory depth');for await(const entry of await opendir(join(directory,relative))){insist(++entries<=1024,'archive entry bound');const path=relative?relative+'/'+entry.name:entry.name;const info=await lstat(join(directory,path));insist(!info.isSymbolicLink(),'archive symlink');if(info.isDirectory())await walk(path,depth+1);else{insist(info.isFile()&&files.length<LIMITS.archiveFiles&&info.size<=LIMITS.fileBytes&&bytes+info.size<=LIMITS.archiveBytes,'archive inventory bounds');const raw=await readFileBounded(directory,path,LIMITS.fileBytes);bytes+=raw.length;files.push({path,bytes:raw.length,sha256:hashBytes(raw)});}}}await walk('',0);return files.sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0);}
async function produceSpawn(binary:string,manifestPath:string,manifestSha:string,resultsRoot?:string){
 const before=await captureSpawnBinding(ROOT,binary,manifestPath,manifestSha);const archive=await mkdtemp(join(tmpdir(),'algal-spawn-conformance-'));const writer=new Writer(archive);const authority={binding:before,recordedArchive:archive,workerPath:join(BASE,'worker.ts'),nativePath:before.native.path,bunPath:before.repository.runtime.path};const rows:unknown[]=[];let commands=0,comparisons=0,replays=0,negativeReplays=0;
 async function command(path:string,argv:string[],inputPaths:string[]=[]){writer.capacity(3*1048576,16);const inputsBefore=await captureInputs(archive,inputPaths);commands++;try{const result=await runCommand(argv,ROOT,{timeoutMs:LIMITS.commandMs,maxOutputBytes:LIMITS.commandBytes});await writer.put(path,result);const inputsAfter=await captureInputs(archive,inputPaths);if(inputPaths.length)await writer.put(path+'.inputs.json',{before:inputsBefore,after:inputsAfter});admitInputs(inputsBefore,inputsAfter);return result;}catch(error){if(error instanceof CommandFailure){try{for(const [name,raw]of [['stdout',error.rawStdout],['stderr',error.rawStderr]]as const){writer.capacity(raw.length,1);writer.bytes+=raw.length;writer.files++;await writeFile(join(archive,path+'.'+name+'.bin'),raw,{flag:'wx',mode:0o600});}await writer.put(path+'.failure.json',{message:error.message,observation:{...error.observation,completion:error.observation.completion??null,drained:error.observation.drained??null,supervisorExit:error.observation.supervisorExit??null}});}catch{/* Preserve the primary custody failure if retention also fails. */}}throw error;}}
 try{
  await writer.put('binding-before.json',before);
  const cases=fixtures();insist(cases.length===17&&new Set(cases.map(f=>f.id)).size===17,'frozen spawn corpus');
  for(const f of cases){const directory=join(archive,f.id);await mkdir(directory);await mkdir(join(directory,'native-state'));await mkdir(join(directory,'verify-state'));
   const state=execute(f.program,f.args,f.budget,f.tape,'none',f.catalog),want=expected(state);
   await writer.put(f.id+'/fixture.json',f);await writer.put(f.id+'/oracle.json',{projection:want,trace:state.trace,effects:state.effects});
   const bunArgs=[authority.bunPath,authority.workerPath,'run',f.id,directory];const bun=await command(f.id+'/bun-run.command.json',bunArgs,[f.id+'/fixture.json',f.id+'/oracle.json']);const bunResult=await readJson(directory,'bun-run-result.json');admitWorker(bun,bunArgs,f.id,'run',bunResult);
   const details=bunResult as {requests:unknown[];selfVerification:unknown};insist(stableJson(Object.keys(details).sort())===stableJson(['requests','selfVerification']),'closed Bun run result');admitProjection(state.effects.map(e=>e.request),details.requests);
   const bunReceipt=await readJson(directory,'bun-receipt.json');admitReplay(details.selfVerification,bunReceipt,true);replays++;
   const immutable:InputFile[]=await captureInputs(directory,['fixture.json','oracle.json','manifest.json','responses.json','args.json','bun-receipt.json','bun-run-result.json']);admitProjection(want,actual(bunReceipt));comparisons++;
   const nativeArgs=[authority.nativePath,'run',join(directory,'manifest.json'),'--responses',join(directory,'responses.json'),'--args',join(directory,'args.json'),'--write','--dir',join(directory,'native-state')];const native=await command(f.id+'/native-run.command.json',nativeArgs,['manifest.json','responses.json','args.json'].map(path=>f.id+'/'+path));const nativeReceipt:unknown=JSON.parse(native.stdout);admitProjection(want,actual(nativeReceipt));const persistedDigest=hashBytes(canonical(nativeReceipt as Json));admitNative(native,nativeArgs,state.outcome==='complete'?0:1,'receipt '+persistedDigest+'\n');comparisons++;await writer.put(f.id+'/native-receipt.json',nativeReceipt);
   const rootWire=canonical(await readJson(directory,'manifest.json') as Json),rootDigest=hashBytes(rootWire);insist((nativeReceipt as {manifestDigest:string}).manifestDigest===rootDigest,'native receipt root manifest identity');await admitRaw(directory,`native-state/manifests/${rootDigest.slice(7)}.json`,rootWire);await admitRaw(directory,`native-state/runs/${persistedDigest.slice(7)}.json`,canonical(nativeReceipt as Json));
   for(const runtime of ['bun','native'])for(const spec of f.catalog){const definition=spawnDefinition(spec);const path=`${runtime}-state/manifests/${definition.digest.slice(7)}.json`;await admitRaw(directory,path,canonical(definition.manifest));}
   for(const runtime of ['bun','native']){const argv=[authority.nativePath,'verify',join(directory,runtime+'-receipt.json'),join(directory,'manifest.json'),'--dir',join(directory,'verify-state')];const out=await command(f.id+'/native-verify-'+runtime+'.command.json',argv,[f.id+'/'+runtime+'-receipt.json',f.id+'/manifest.json']);admitNative(out,argv,0);admitReplay(JSON.parse(out.stdout),await readJson(directory,runtime+'-receipt.json'),true);replays++;}
   const verifyArgs=[authority.bunPath,authority.workerPath,'verify',f.id,directory];const checked=await command(f.id+'/bun-verify.command.json',verifyArgs,[f.id+'/native-receipt.json',f.id+'/manifest.json']);const verifyResult=await readJson(directory,'bun-verify-result.json');admitWorker(checked,verifyArgs,f.id,'verify',verifyResult);admitReplay(verifyResult,nativeReceipt,true);replays++;
   if(f.id==='two-success'){
    const args=[authority.bunPath,authority.workerPath,'mutations',f.id,directory];const out=await command(f.id+'/bun-mutations.command.json',args,[f.id+'/bun-receipt.json',f.id+'/manifest.json']);const result=await readJson(directory,'bun-mutations-result.json');admitWorker(out,args,f.id,'mutations',result);insist(Array.isArray(result)&&result.length===2,'Bun mutation result count');for(const [i,row]of result.entries()){insist(row&&typeof row==='object'&&stableJson(Object.keys(row).sort())===stableJson(['mode','report'])&&row.mode===['reordered','duplicated'][i],'closed Bun mutation result');admitReplay(row.report,bunReceipt,false);}negativeReplays+=2;
    for(const mutation of ['reordered','duplicated']){const argv=[authority.nativePath,'verify',join(directory,mutation+'-receipt.json'),join(directory,'manifest.json'),'--dir',join(directory,'verify-state')];const checked=await command(f.id+'/native-'+mutation+'.command.json',argv,[f.id+'/'+mutation+'-receipt.json',f.id+'/manifest.json']);admitNative(checked,argv,1);admitReplay(JSON.parse(checked.stdout),nativeReceipt,false);negativeReplays++;}
   }
   admitInputs(immutable,await captureInputs(directory,immutable.map(file=>file.path)));
   for(const runtime of ['bun','native'])for(const spec of f.catalog){const definition=spawnDefinition(spec);await admitRaw(directory,`${runtime}-state/manifests/${definition.digest.slice(7)}.json`,canonical(definition.manifest));}
   const files=await inventory(archive);writer.bytes=files.reduce((sum,f)=>sum+f.bytes,0);writer.files=files.length;rows.push({id:f.id,outcome:state.outcome,effects:state.effects.length,work:state.work});
  }
  const after=await captureSpawnBinding(ROOT,binary,manifestPath,manifestSha);insist(hashJson(before)===hashJson(after),'source/tool/artifact drift');await writer.put('binding-after.json',after);const files=await inventory(archive);insist(comparisons===34&&replays===68&&negativeReplays===4&&commands===88,'closed qualification counts');const result={contract:CONTRACT,ok:true,archive,cases:17,comparisons,replays,negativeReplays,commands,limits:LIMITS,rows,files,scope:RELATION};await writer.put('summary.json',result);const admission=await readmitArchive(archive,authority);insist(hashJson(before)===hashJson(await captureSpawnBinding(ROOT,binary,manifestPath,manifestSha)),'source/tool/artifact drift during readmission');return {result,admission,authority};
 }catch(error){return retainFailure(error,[
  ()=>writer.put('failure.json',{error:String(error).slice(0,4096),commands,comparisons,replays,negativeReplays,rows}),
  ...(resultsRoot?[async()=>{await retainEvidence({resultsRoot,suite:'spawn-conformance',sourceRoot:archive,recordedArchive:authority.recordedArchive,authorityDigest:hashJson(authority),limits:{maxBytes:LIMITS.archiveBytes,maxFileBytes:LIMITS.fileBytes,maxEntries:1024,maxDepth:8},classification:'diagnostic'});}]:[]),
 ]);}
}
export async function runSpawn(binary:string,manifestPath:string,manifestSha:string){const {result,admission}=await produceSpawn(binary,manifestPath,manifestSha);return {...result,admission};}
if(import.meta.main){const [binary,manifest,sha]=process.argv.slice(2);insist(process.argv.length===5&&binary&&manifest&&sha&&/^sha256:[a-f0-9]{64}$/.test(sha),'explicit frozen CLI/build-manifest/hash required');const {admission:_admission,...result}=await runSpawn(binary,manifest,sha);console.log(stableJson({ok:true,archive:result.archive,cases:result.cases,comparisons:result.comparisons,replays:result.replays,negativeReplays:result.negativeReplays,commands:result.commands,summarySha256:hashBytes(encoded(result))}));}

export async function runSpawnConformance(root:string,binary=process.env.ALGAL_SPAWN_NATIVE_BIN,manifest=process.env.ALGAL_SPAWN_BUILD_MANIFEST,sha=process.env.ALGAL_SPAWN_BUILD_MANIFEST_SHA256,resultsRoot=join(root,'verify/results')){
 insist(resolve(root)===ROOT&&binary&&manifest&&sha,'spawn conformance requires explicit root, native binary, build manifest and manifest hash');
 const {result,authority}=await produceSpawn(binary,manifest,sha,resultsRoot);
 const selection={resultsRoot,suite:'spawn-conformance',sourceRoot:result.archive,recordedArchive:authority.recordedArchive,authorityDigest:hashJson(authority),limits:{maxBytes:LIMITS.archiveBytes,maxFileBytes:LIMITS.fileBytes,maxEntries:1024,maxDepth:8}};
 try{
 const evidence=await retainEvidence({...selection,classification:'admitted',readmit:async physicalRoot=>{
  const admission=await readmitArchive(physicalRoot,authority);
  insist(hashJson(authority.binding)===hashJson(await captureSpawnBinding(ROOT,binary,manifest,sha)),'source/tool/artifact drift during retained readmission');return admission;
 }});
 return {contract:result.contract,ok:result.ok,archive:result.archive,cases:result.cases,comparisons:result.comparisons,replays:result.replays,negativeReplays:result.negativeReplays,commands:result.commands,summarySha256:hashBytes(encoded(result)),admission:evidence.admission,evidence,scope:RELATION};
 }catch(error){return retainFailure(error,[async()=>{await retainEvidence({...selection,classification:'diagnostic'});}]);}
}
