pub mod acp;
pub mod application;
pub mod application_adaptation;
pub mod application_comparison;
pub mod application_drain;
pub mod application_episode;
pub mod application_experiment;
pub mod application_goal;
pub mod application_host;
pub mod application_memory;
pub mod application_migration;
pub mod application_proposal;
mod application_quota;
pub mod application_report;
pub mod application_restoration;
pub mod application_selection;
pub mod application_view;
pub mod application_view_evidence;
pub mod bench;
pub mod build_info;
pub mod canonical;
pub mod capabilities;
pub mod civilization;
pub mod context;
pub mod contract;
pub mod credentials;
pub mod decisions;
pub mod demo;
pub mod effects;
pub mod embeddings;
pub mod error;
pub mod foundry;
pub mod graph;
pub mod journal;
mod lease;
pub mod mailbox;
pub mod memory;
pub mod process;
pub mod process_evidence;
pub mod receipt;
pub mod registry;
pub mod runtime;
pub mod scorer;
pub mod semantic;
pub mod store;
pub mod suite;

pub use error::{Error, Result};

pub mod demo_report;
