pub mod acp;
pub mod application;
pub mod application_adaptation;
pub mod application_host;
pub mod application_memory;
pub mod application_migration;
pub mod bench;
pub mod build_info;
pub mod canonical;
pub mod capabilities;
pub mod civilization;
pub mod context;
pub mod contract;
pub mod credentials;
pub mod decisions;
pub mod demo;
pub mod effects;
pub mod embeddings;
pub mod error;
pub mod foundry;
pub mod graph;
pub mod journal;
mod lease;
pub mod mailbox;
pub mod memory;
pub mod process;
pub mod process_evidence;
pub mod registry;
pub mod runtime;
pub mod scorer;
pub mod semantic;
pub mod store;
pub mod suite;

pub use error::{Error, Result};

pub mod demo_report;
