import { afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, rm, symlink, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { parseBundle, unpackBundle } from "../../src/bundle";
import modelEvidence from "./model-evidence.json";
import modelProposal from "./model-proposal.json";
import { parseProposal } from "./surface";
import { applicationJson } from "../../src/application-contract";
import { createBudgetedExecutor } from "../coding-harness/inference-budget";
import { generateProposal } from "./propose";
import { digestCanonical } from "../../src/digest";
import { APPLICATION, MarketingHost, exportEvidence, signalOperation, verifyEvidence } from "./host";
import { DEFAULT_CONFIG, DEFAULT_SIGNALS, type SurfaceProposal } from "./surface";
import { evaluateShadow } from "./shadow";
import { MarketingWorkbench, exportWorkbenchEvidence, verifyWorkbenchEvidence } from "./workbench";
import { DEFAULT_CONTROLS, parseWorkbenchCapture, parseWorkbenchCommand, type SignalEnvelope, type WorkbenchCapture, type WorkbenchCommand } from "./workbench-contract";
const directories: string[] = [], hash = (input: unknown) => digestCanonical(applicationJson(input));
afterEach(async () => { for (const path of directories.splice(0)) await rm(path, { recursive: true, force: true }); });
async function fixture() { const directory = await mkdtemp(join(tmpdir(), "algal-workbench-test-")); directories.push(directory); const host = new MarketingHost(directory); await host.initialize(); const bundle = parseBundle(modelEvidence.bundle); await unpackBundle(bundle, host.service.store); return { directory, host, workbench: new MarketingWorkbench(host), manifest: bundle.root }; }
function proposal(capture: WorkbenchCapture, source: "owner" | "model" = "owner"): SurfaceProposal { return { contract: "algal.marketing-proposal.v1", baseRevision: capture.revisionDigest, config: { ...DEFAULT_CONFIG, headline: "A component with retained reasons." }, source, rationale: "Explicit fixture for admission behavior." }; }
function command(capture: WorkbenchCapture, value: Record<string, unknown>): WorkbenchCommand { return parseWorkbenchCommand({ contract: "algal.marketing-command.v1", actor: "human", operation: hash(value), expectedHead: capture.head, expectedControls: capture.controlsRef, ...value }); }
const envelope = (sequence: number, value: "builders" | "operators" = "operators"): SignalEnvelope => ({ contract: "algal.marketing-signal-envelope.v1", source: "environment", stream: "audience", sequence, event: { kind: "audience", value } });
describe("same-head marketing workbench", () => {
  test("captures history once and explains the terminal snapshot despite a concurrent advance", async () => {
    const f = await fixture(), original = f.host.service.history.bind(f.host.service); let reads = 0;
    f.host.service.history = async (application) => { reads++; const rows = await original(application); if (reads === 1) await new MarketingHost(f.directory).signal(rows.at(-1)!.digest, { kind: "audience", value: "operators" }, hash("concurrent")); return rows; };
    const capture = await f.workbench.capture();
    expect(reads).toBe(1); expect(capture.sequence).toBe(0); expect(capture.signals).toEqual(DEFAULT_SIGNALS);
    expect(capture.history.at(-1)?.head).toBe(capture.head);
    expect(capture.provenance.nodes.find(row => row.node === "audience")?.signalFields).toEqual(["audience"]);
    expect(capture.provenance.nodes.every(row => row.revision === capture.revisionDigest && row.receipt === capture.provenance.receipt)).toBe(true);
    expect((await new MarketingHost(f.directory).current()).digest).not.toBe(capture.head);
  }, 30_000);
  test("ordered signals deduplicate across restart and restore; conflicts, gaps and unknown identities fail", async () => {
    const f = await fixture(), start = await f.workbench.capture(), first = envelope(1);
    const changed = await f.workbench.execute(command(start, { kind: "signal", envelope: first, operation: signalOperation(first) }));
    expect(changed.capture.signals.audience).toBe("operators"); expect(changed.capture.provenance.cursors[0]?.sequence).toBe(1);
    const reopened = new MarketingWorkbench(new MarketingHost(f.directory));
    expect((await reopened.host.signalEnvelope(start.head, first)).digest).toBe(changed.capture.head);
    await expect(reopened.host.signalEnvelope(changed.capture.head, envelope(1, "builders"))).rejects.toThrow("different content");
    await expect(reopened.host.signalEnvelope(changed.capture.head, envelope(3))).rejects.toThrow("sequence");
    await expect(reopened.execute(command(changed.capture, { kind: "signal", envelope: first, operation: hash("unbound") }))).rejects.toThrow("derive");
    expect(() => command(changed.capture, { kind: "signal", envelope: { ...first, source: "untrusted" } })).toThrow();
    const p = await reopened.execute(command(changed.capture, { kind: "preview", proposal: proposal(changed.capture) }));
    const active = await reopened.execute(command(p.capture, { kind: "activate", preview: p.preview!.reference }));
    const restored = await reopened.execute(command(active.capture, { kind: "restore", targetState: start.head }));
    expect(restored.capture.signals.audience).toBe("operators"); expect(restored.capture.provenance.cursors).toEqual(changed.capture.provenance.cursors);
    const duplicate = await reopened.execute(command(start, { kind: "signal", envelope: first, operation: signalOperation(first) }));
    expect(duplicate.capture.head).toBe(restored.capture.head);
    const second = await reopened.host.signalEnvelope(restored.capture.head, envelope(2, "builders")); expect((await reopened.host.signals(second)).audience).toBe("builders");
    await expect(reopened.host.signal(second.digest, { kind: "release", value: "available" }, hash("legacy"))).rejects.toThrow("ordered");
    expect(await verifyEvidence(await exportEvidence(reopened.host), second.digest)).toMatchObject({ ok: true, states: 5 });
  }, 30_000);
  test("model freeze preserves owner edits; pin and controls cannot be bypassed by direct service commits", async () => {
    const f = await fixture(), initial = await f.workbench.capture();
    const frozen = await f.workbench.execute(command(initial, { kind: "set-controls", controls: { ...DEFAULT_CONTROLS, modelActivationPaused: true } }));
    const model = await f.host.preview(frozen.capture.head, proposal(frozen.capture, "model"));
    await expect(f.host.activate(model.reference, hash("model"))).rejects.toThrow("paused");
    const parent = await f.host.current();
    await expect(f.host.service.commit({ application: APPLICATION, operation: hash("direct"), kind: "activate", expectedHead: parent.digest, revision: model.record.candidateRevision, memory: parent.state.memory, intents: [], evidence: [model.reference], causedBy: null })).rejects.toThrow("paused");
    const owner = await f.workbench.execute(command(frozen.capture, { kind: "preview", proposal: proposal(frozen.capture) }));
    const edited = await f.workbench.execute(command(owner.capture, { kind: "activate", preview: owner.preview!.reference }));
    const pinned = await f.workbench.execute(command(edited.capture, { kind: "set-controls", controls: { ...DEFAULT_CONTROLS, pinnedRevision: edited.capture.revisionDigest } }));
    await expect(f.host.restore(pinned.capture.head, initial.head, hash("pinned-restore"))).rejects.toThrow("pinned");
    await expect(f.workbench.execute(command(pinned.capture, { kind: "set-controls", actor: "agent", controls: DEFAULT_CONTROLS }))).rejects.toThrow("owner");
    await expect(f.workbench.execute(command(initial, { kind: "set-controls", controls: DEFAULT_CONTROLS }))).rejects.toThrow("Stale");
    const current = await f.host.current(), raw = await f.host.service.store.getValue(current.state.memory);
    const downgrade = await f.host.service.store.putValue(applicationJson({ contract: "algal.marketing-memory.v1", signals: pinned.capture.signals, previous: current.state.memory, event: null, receipt: null }));
    await expect(f.host.service.commit({ application: APPLICATION, operation: hash("downgrade"), kind: "memory", expectedHead: current.digest, revision: current.state.revision, memory: downgrade, intents: [], evidence: [hash("invalid")], causedBy: null })).rejects.toThrow();
    expect(raw).toHaveProperty("contract", "algal.marketing-memory.v2");
  }, 30_000);
  test("pausing blocks new inference but admitted settlement survives restart; no uncertain retry", async () => {
    const f = await fixture(), initial = await f.workbench.capture(), admission = { operation: hash("attempt"), expectedHead: initial.head, expectedControls: initial.controlsRef, manifest: f.manifest, backend: "local" as const, model: "fixture" };
    const attempt = await f.workbench.beginAttempt(admission);
    await expect(f.workbench.beginAttempt(admission)).rejects.toThrow("already admitted");
    await expect(f.workbench.beginAttempt({ ...admission, operation: hash("second") })).rejects.toThrow("Pending");
    const paused = await f.workbench.execute(command(initial, { kind: "set-controls", controls: { ...DEFAULT_CONTROLS, inferencePaused: true } }));
    const reopened = new MarketingWorkbench(new MarketingHost(f.directory));
    await reopened.finishAttempt(attempt, { status: "uncertain", proposal: null, receipt: null, accounting: null, reason: "Fixture terminated after admission; external completion unknown." });
    await reopened.finishAttempt(attempt, { status: "uncertain", proposal: null, receipt: null, accounting: null, reason: "Fixture terminated after admission; external completion unknown." });
    await expect(reopened.finishAttempt(attempt, { status: "failed", proposal: null, receipt: null, accounting: null, reason: "Conflict" })).rejects.toThrow("conflicts");
    const capture = await reopened.capture(); expect(capture.observation.uncertainAttempts).toBe(1); expect(capture.observation.actualCostMicrousd).toBeNull();
    expect(capture.actions.find(row => row.kind === "infer")?.allowed).toBe(false);
    await expect(reopened.beginAttempt({ ...admission, operation: hash("paused"), expectedHead: paused.capture.head, expectedControls: paused.capture.controlsRef })).rejects.toThrow("paused");
  }, 30_000);
  test("retains previews, failed attempts and shadow records in a replayable bounded evidence export", async () => {
    const f = await fixture(), initial = await f.workbench.capture(), p = proposal(initial);
    await f.workbench.execute(command(initial, { kind: "preview", proposal: p }));
    const attempt = await f.workbench.beginAttempt({ operation: hash("failed"), expectedHead: initial.head, expectedControls: initial.controlsRef, manifest: f.manifest, backend: "gateway", model: "fixture" });
    await f.workbench.finishAttempt(attempt, { status: "failed", proposal: null, receipt: null, accounting: null, reason: "Fixture rejected before provider dispatch." });
    const policy = await f.host.service.store.putValue({ fixture: "policy" }), evidence = await f.host.service.store.putValue({ fixture: "failed constraint" });
    const shadow = { operation: hash("shadow"), parentState: initial.head, proposal: p, accepted: false, policy, evidence, reason: "Offline fixture rejects an unchanged candidate." };
    expect(await f.workbench.recordShadow(shadow)).toBe(await f.workbench.recordShadow(shadow));
    const exported = await exportWorkbenchEvidence(f.workbench);
    expect(await verifyWorkbenchEvidence(exported, initial.head)).toMatchObject({ ok: true, journalEntries: 4 });
    const tampered = structuredClone(exported); tampered.journal[0]!.previous = hash("missing");
    await expect(verifyWorkbenchEvidence(tampered, initial.head)).rejects.toThrow("chain");
    const missing = structuredClone(exported); missing.records = missing.records.filter(row => row.reference !== evidence);
    await expect(verifyWorkbenchEvidence(missing, initial.head)).rejects.toThrow("shadow");
    const capture = await new MarketingWorkbench(new MarketingHost(f.directory)).capture();
    expect(capture.previews).toHaveLength(1); expect(capture.attempts).toHaveLength(1); expect(capture.shadows).toHaveLength(1);
  }, 30_000);
  test("closed parsers reject authority additions, forged totals and malformed captures", async () => {
    const f = await fixture(), capture = await f.workbench.capture();
    expect(() => parseWorkbenchCapture({ ...capture, token: "secret" })).toThrow();
    expect(() => command(capture, { kind: "preview", proposal: { ...proposal(capture), controls: DEFAULT_CONTROLS } })).toThrow();
    expect(() => parseWorkbenchCapture({ ...capture, history: [] })).toThrow("history");
    expect(() => parseWorkbenchCapture({ ...capture, observation: { ...capture.observation, actualCostMicrousd: 0 } })).toThrow("unknown");
    expect(() => parseWorkbenchCapture({ ...capture, provenance: { ...capture.provenance, cursors: Array.from({ length: 17 }, () => ({ source: "demo", stream: "x", sequence: 1, envelope: hash("x") })) } })).toThrow("bound");
  }, 30_000);
  test("reconciliation retains uncertainty and accepts only the same replayed execution and settled accounting", async () => {
    const f = await fixture(), capture = await f.workbench.capture();
    const admission = { operation: hash("reconcile"), expectedHead: capture.head, expectedControls: capture.controlsRef, manifest: f.manifest, backend: "gateway" as const, model: modelEvidence.model };
    const attempt = await f.workbench.beginAttempt(admission);
    const uncertain = { ...modelEvidence.accounting, completedCalls: 0, inputTokens: null, outputTokens: null, stopped: true, records: modelEvidence.accounting.records.map(row => ({ ...row, status: "unknown", tokensIn: null, tokensOut: null, outputDigest: null })) };
    const prior = await f.host.service.store.putValue(applicationJson(uncertain));
    await f.workbench.finishAttempt(attempt, { status: "uncertain", proposal: null, receipt: null, accounting: prior, reason: "Captured completion was not yet reconciled." });
    const receipt = await f.host.service.store.putReceipt(applicationJson(modelEvidence.receipt)), accounting = await f.host.service.store.putValue(applicationJson(modelEvidence.accounting));
    const complete = { status: "completed" as const, proposal: parseProposal(modelProposal), receipt, accounting, reason: null };
    await expect(f.workbench.reconcileAttempt(attempt, { ...complete, receipt: capture.provenance.receipt })).rejects.toThrow("admitted execution");
    const changed = await f.host.service.store.putValue(applicationJson({ ...modelEvidence.accounting, configurationDigest: hash("other-execution") }));
    await expect(f.workbench.reconcileAttempt(attempt, { ...complete, accounting: changed })).rejects.toThrow("identities");
    await f.workbench.reconcileAttempt(attempt, complete);
    await f.workbench.reconcileAttempt(attempt, complete);
    const reopened = new MarketingWorkbench(new MarketingHost(f.directory)), after = await reopened.capture();
    expect(after.attempts[0]?.settlements.map(row => row.outcome.status)).toEqual(["uncertain", "completed"]);
    expect(after.observation.completedAttempts).toBe(1); expect(after.observation.usage[0]).toMatchObject({ reservedMicrousd: 38912, inputTokens: 949, outputTokens: 95 });
    expect(after.observation.actualCostMicrousd).toBeNull();
    expect(await verifyWorkbenchEvidence(await exportWorkbenchEvidence(reopened), capture.head)).toMatchObject({ ok: true, journalEntries: 3 });
  }, 30_000);
  test("workbench model adoption requires both exact inference and replayed passing shadow", async () => {
    const f = await fixture(), capture = await f.workbench.capture(), p = parseProposal(modelProposal);
    const preview = await f.workbench.execute(command(capture, { kind: "preview", proposal: p }));
    const adopt = command(capture, { kind: "activate", preview: preview.preview!.reference });
    await expect(f.workbench.execute(adopt)).rejects.toThrow("inference attempt");
    const attempt = await f.workbench.beginAttempt({ operation: hash("model-qualified"), expectedHead: capture.head, expectedControls: capture.controlsRef, manifest: f.manifest, backend: "gateway", model: modelEvidence.model });
    const receipt = await f.host.service.store.putReceipt(applicationJson(modelEvidence.receipt)), accounting = await f.host.service.store.putValue(applicationJson(modelEvidence.accounting));
    await f.workbench.finishAttempt(attempt, { status: "completed", proposal: p, receipt, accounting, reason: null });
    await expect(f.workbench.execute(adopt)).rejects.toThrow("shadow evidence");
    const { reference, report } = await evaluateShadow(f.host, capture.head, p);
    await f.workbench.recordShadow({ operation: hash("qualified-shadow"), parentState: capture.head, proposal: p, accepted: true, policy: report.policy, evidence: reference, reason: "Host-owned offline constraints passed; no optimization claim." });
    const original = f.host.service.history.bind(f.host.service); let reads = 0;
    f.host.service.history = async (application) => { reads++; return original(application); };
    const ready = await f.workbench.capture(); expect(reads).toBe(1); expect(ready.actions.find(row => row.kind === "activate")?.allowed).toBe(true);
    const activated = await f.workbench.execute(adopt); expect(activated.capture.revision.config).toEqual(p.config);
    expect((await f.workbench.execute(adopt)).capture.head).toBe(activated.capture.head);
  }, 30_000);
  test("completed inference cannot relabel the gateway configuration as another backend", async () => {
    const f = await fixture(), capture = await f.workbench.capture();
    const attempt = await f.workbench.beginAttempt({ operation: hash("relabelled-provider"), expectedHead: capture.head, expectedControls: capture.controlsRef, manifest: f.manifest, backend: "local", model: modelEvidence.model });
    const receipt = await f.host.service.store.putReceipt(applicationJson(modelEvidence.receipt)), accounting = await f.host.service.store.putValue(applicationJson(modelEvidence.accounting));
    await expect(f.workbench.finishAttempt(attempt, { status: "completed", proposal: parseProposal(modelProposal), receipt, accounting, reason: null })).rejects.toThrow("admitted backend");
    expect((await f.workbench.capture()).observation.completedAttempts).toBe(0);
  }, 30_000);
  test("journal exhaustion reserves uncertain settlement and reconciliation without pruning", async () => {
    const f = await fixture(), capture = await f.workbench.capture(), p = proposal(capture);
    const policy = await f.host.service.store.putValue({ fixture: "policy" }), evidence = await f.host.service.store.putValue({ fixture: "evidence" });
    for (let index = 0; index < 125; index++) await f.workbench.recordShadow({ operation: hash({ index }), parentState: capture.head, proposal: p, accepted: false, policy, evidence, reason: "Bounded fixture." });
    const attempt = await f.workbench.beginAttempt({ operation: hash("reserved-final"), expectedHead: capture.head, expectedControls: capture.controlsRef, manifest: f.manifest, backend: "gateway", model: modelEvidence.model });
    await expect(f.workbench.recordShadow({ operation: hash("over-reservation"), parentState: capture.head, proposal: p, accepted: false, policy, evidence, reason: "No capacity." })).rejects.toThrow("reserved");
    const uncertain = { ...modelEvidence.accounting, completedCalls: 0, inputTokens: null, outputTokens: null, stopped: true, records: modelEvidence.accounting.records.map(row => ({ ...row, status: "unknown", tokensIn: null, tokensOut: null, outputDigest: null })) };
    const prior = await f.host.service.store.putValue(applicationJson(uncertain));
    await f.workbench.finishAttempt(attempt, { status: "uncertain", proposal: null, receipt: null, accounting: prior, reason: "Unknown completion retains its reconciliation slot." });
    expect((await f.workbench.capture()).observation.journalEntries).toBe(127);
    await expect(f.workbench.recordShadow({ operation: hash("reserved-reconciliation"), parentState: capture.head, proposal: p, accepted: false, policy, evidence, reason: "No spare reconciliation slot." })).rejects.toThrow("reserved");
    const receipt = await f.host.service.store.putReceipt(applicationJson(modelEvidence.receipt)), accounting = await f.host.service.store.putValue(applicationJson(modelEvidence.accounting));
    await f.workbench.reconcileAttempt(attempt, { status: "completed", proposal: parseProposal(modelProposal), receipt, accounting, reason: null });
    const after = await new MarketingWorkbench(new MarketingHost(f.directory)).capture();
    expect(after.observation.journalEntries).toBe(128); expect(after.shadows).toHaveLength(125); expect(after.attempts[0]!.settlements).toHaveLength(2);
    await expect(f.workbench.execute(command(after, { kind: "preview", proposal: p }))).rejects.toThrow("exhausted");
  }, 60_000);
  test("64 retained states remain visible and a 65th is denied without head movement", async () => {
    const f = await fixture(); let current = await f.host.current();
    for (let index = 1; index < 64; index++) current = await f.host.signalEnvelope(current.digest, envelope(index, index % 2 ? "operators" : "builders"));
    const full = await f.workbench.capture(); expect(full.history).toHaveLength(64); expect(full.sequence).toBe(63);
    await expect(f.host.signalEnvelope(full.head, envelope(64))).rejects.toThrow("bounds");
    expect((await f.host.current()).digest).toBe(full.head);
    expect((await new MarketingWorkbench(new MarketingHost(f.directory)).capture()).history).toHaveLength(64);
    expect(full.actions.filter(row => ["activate", "signal", "restore", "set-controls"].includes(row.kind)).every(row => !row.allowed)).toBe(true);
  }, 60_000);
  test("journal filesystem refuses symlinks instead of reading external state", async () => {
    const f = await fixture(); await f.workbench.capture();
    await symlink(join(f.directory, "nonexistent"), join(f.workbench.directory, "records", "000.json"));
    await expect(f.workbench.capture()).rejects.toThrow("entry type");
  }, 30_000);
  test("settlement failure retains the observed receipt and reconciles without another model call", async () => {
    const f = await fixture(), capture = await f.workbench.capture(), output = { ...proposal(capture, "model").config, rationale: "One retained simulated response." };
    const config = { provider: "gateway", model: "fixture", gatewayProvider: "fixture", ledgerPath: join(f.directory, "backend-ledger"), maxCalls: 1, maxCostMicrousd: 100_000, maxInputTokens: 16384, maxOutputTokens: 256, inputMicrousdPerToken: 1, outputMicrousdPerToken: 1, maxRequestBytes: 32768, maxOutputBytes: 4096 };
    let calls = 0;
    const factory = async () => {
      const backend = await createBudgetedExecutor({ ledgerPath: config.ledgerPath, budget: { maxCalls: 1, maxCostMicrousd: 1, reserveMicrousdPerCall: 1 }, maxRequestBytes: config.maxRequestBytes, maxOutputBytes: config.maxOutputBytes, executor: { id: "vercel:fixture", execute: async () => output, executeEffect: async () => { calls++; return { output, metadata: { executor: "vercel:fixture", usage: { tokensIn: 1, tokensOut: 1 } } }; } } });
      return { ...backend, settle: async () => { await backend.settle(); throw new Error("Simulated settlement acknowledgement failure"); } };
    };
    await expect(generateProposal(f.host, config, factory)).rejects.toThrow("uncertain");
    const after = await f.workbench.capture(), attempt = after.attempts[0]!;
    expect(attempt.settlement?.status).toBe("uncertain");
    expect(attempt.settlement?.receipt).not.toBeNull();
    expect(await f.host.service.store.getReceipt(attempt.settlement!.receipt!)).toBeDefined();
    const p = parseProposal({ ...proposal(capture, "model"), rationale: output.rationale });
    await f.workbench.reconcileAttempt(attempt.reference, { status: "completed", proposal: p, receipt: attempt.settlement!.receipt, accounting: attempt.settlement!.accounting, reason: null });
    await expect(generateProposal(f.host, config, factory)).rejects.toThrow("already admitted");
    expect(calls).toBe(1);
    expect((await f.workbench.capture()).attempts[0]!.settlements.map(row => row.outcome.status)).toEqual(["uncertain", "completed"]);
  }, 30_000);
  test("failed settlements cannot discard unknown accounting and pending exports require admitted manifests", async () => {
    const f = await fixture(), capture = await f.workbench.capture();
    const attempt = await f.workbench.beginAttempt({ operation: hash("unknown-not-failed"), expectedHead: capture.head, expectedControls: capture.controlsRef, manifest: f.manifest, backend: "gateway", model: modelEvidence.model });
    const uncertain = { ...modelEvidence.accounting, completedCalls: 0, inputTokens: null, outputTokens: null, stopped: true, records: modelEvidence.accounting.records.map(row => ({ ...row, status: "reserved", tokensIn: null, tokensOut: null, outputDigest: null })) };
    const accounting = await f.host.service.store.putValue(applicationJson(uncertain));
    await expect(f.workbench.finishAttempt(attempt, { status: "failed", proposal: null, receipt: null, accounting, reason: "Cannot dismiss retained unknown execution." })).rejects.toThrow("uncertain");
    expect((await f.workbench.capture()).observation.pendingAttempts).toBe(1);
    const exported = await exportWorkbenchEvidence(f.workbench);
    exported.records = exported.records.filter(row => row.reference !== f.manifest);
    await expect(verifyWorkbenchEvidence(exported, capture.head)).rejects.toThrow("manifest");
  }, 30_000);
  for (const point of ["journal-prepared", "journal-record-published", "journal-committed"] as const) test(`journal resumes ${point} without forgetting admission or rerunning inference`, async () => {
    const f = await fixture(), capture = await f.workbench.capture(), interrupted = new MarketingWorkbench(f.host, { fault(at) { if (at === point) throw new Error(point); } });
    const admission = { operation: hash(point), expectedHead: capture.head, expectedControls: capture.controlsRef, manifest: f.manifest, backend: "gateway" as const, model: modelEvidence.model };
    await expect(interrupted.beginAttempt(admission)).rejects.toThrow(point);
    const reopened = new MarketingWorkbench(new MarketingHost(f.directory)), pending = await reopened.capture();
    expect(pending.observation.pendingAttempts).toBe(1);
    await expect(reopened.beginAttempt(admission)).rejects.toThrow("already admitted");
    await reopened.finishAttempt(pending.attempts[0]!.reference, { status: "failed", proposal: null, receipt: null, accounting: null, reason: "Interrupted before any provider execution in this fixture." });
    expect((await reopened.capture()).observation.failedAttempts).toBe(1);
    const checkpoint = JSON.parse(await readFile(join(reopened.directory, "state.json"), "utf8"));
    expect(checkpoint).toMatchObject({ count: 2, prepared: null, phase: "ready" });
    expect(await Bun.file(join(reopened.directory, "records", "000.json")).exists()).toBe(true);
    expect(await verifyWorkbenchEvidence(await exportWorkbenchEvidence(reopened), capture.head)).toMatchObject({ ok: true, journalEntries: 2 });
  }, 30_000);
  test("journal checkpoint detects deleted committed tail and missing checkpoint; legacy prefix upgrades explicitly", async () => {
    const f = await fixture(), capture = await f.workbench.capture(), p = proposal(capture);
    const policy = await f.host.service.store.putValue({ fixture: "policy" }), evidence = await f.host.service.store.putValue({ fixture: "evidence" });
    const row = { operation: hash("legacy-prefix"), parentState: capture.head, proposal: p, accepted: false, policy, evidence, reason: "Retained observation." };
    await f.workbench.recordShadow(row);
    const anchor = hash({ contract: "algal.marketing-journal-anchor.v1", application: APPLICATION });
    await rm(join(f.workbench.directory, "state.json")); await rm(join(f.directory, "values", `${anchor.slice(7)}.json`)); // Simulate a pre-checkpoint v1 journal.
    expect((await f.workbench.capture()).gaps.some(gap => gap.includes("Legacy journal"))).toBe(true);
    await f.workbench.recordShadow({ ...row, operation: hash("after-upgrade") });
    const tail = join(f.workbench.directory, "records", "001.json"), bytes = await readFile(tail);
    await rm(tail);
    await expect(f.workbench.journal()).rejects.toThrow("Missing committed");
    expect(await Bun.file(tail).exists()).toBe(false);
    await writeFile(tail, bytes);
    await rm(join(f.workbench.directory, "state.json"));
    await expect(f.workbench.journal()).rejects.toThrow("checkpoint");
    expect(await Bun.file(join(f.workbench.directory, "state.json")).exists()).toBe(false);
  }, 30_000);
  test("surface metadata and duplicate previews are checked before any replay can recreate them", async () => {
    const f = await fixture(), capture = await f.workbench.capture(), request = command(capture, { kind: "preview", proposal: proposal(capture) });
    const preview = (await f.workbench.execute(request)).preview!;
    const receiptPath = join(f.directory, "runs", `${preview.receipt.slice(7)}.json`); await rm(receiptPath);
    await expect(f.workbench.capture()).rejects.toThrow("retained preview receipt");
    await expect(f.workbench.execute(request)).rejects.toThrow("receipt");
    expect(await Bun.file(receiptPath).exists()).toBe(false);
    const current = await f.host.current(), schemaPath = join(f.directory, "values", `${current.revision.schema.slice(7)}.json`); await rm(schemaPath);
    await expect(f.host.revision()).rejects.toThrow();
    expect(await Bun.file(schemaPath).exists()).toBe(false);
  }, 30_000);
  test("capture cannot heal an active preview receipt even when owner activation bypasses the journal", async () => {
    const f = await fixture(), capture = await f.workbench.capture();
    const preview = await f.host.preview(capture.head, proposal(capture));
    await f.host.activate(preview.reference, hash("legacy-owner-activation"));
    const receiptPath = join(f.directory, "runs", `${preview.record.receipt.slice(7)}.json`);
    await rm(receiptPath);
    await expect(f.workbench.capture()).rejects.toThrow("receipt");
    expect(await Bun.file(receiptPath).exists()).toBe(false);
    await expect(f.host.render()).rejects.toThrow("receipt");
    expect(await Bun.file(receiptPath).exists()).toBe(false);
  }, 30_000);
  test("capture checks accepted shadow receipts before a fresh incumbent render can recreate them", async () => {
    const f = await fixture(), capture = await f.workbench.capture(), p = proposal(capture);
    const evaluated = await evaluateShadow(f.host, capture.head, p);
    await f.workbench.recordShadow({ operation: hash("capture-shadow"), parentState: capture.head, proposal: p, accepted: true, policy: evaluated.report.policy, evidence: evaluated.reference, reason: "Retained passing guardrails." });
    const row = evaluated.report.cases.find(value => hash(value.signals) === hash(capture.signals))!;
    expect(row.incumbentReceipt).toBe(capture.provenance.receipt);
    const receiptPath = join(f.directory, "runs", `${row.incumbentReceipt.slice(7)}.json`);
    await rm(receiptPath);
    await expect(f.workbench.capture()).rejects.toThrow("shadow receipt");
    expect(await Bun.file(receiptPath).exists()).toBe(false);
  }, 30_000);

});
